Repository hmcts/darts-portal, pull requests merged in 2023-12, with the labels that each got.

#611 DMP-1457 TOTP B2C Screen
  server/assets/javascripts/errors.js
  server/assets/javascripts/mfa.js
  server/assets/stylesheets/mfa.css
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-611

#610 Fix repeated style - .govuk-table__cell padding
  src/app/components/audios/audio-view/audio-view.component.scss
  src/app/components/audios/audios.component.scss
  src/app/components/common/data-table/data-table.component.scss
  src/app/components/hearing/hearing.component.scss
  src/app/components/hearing/request-transcript/request-transcript.component.scss
  src/app/components/search/results/results.component.scss
  src/app/components/transcriptions/transcriptions.component.scss
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-610

#618 DMP-1234-Assign-Transcript-Order
  src/app/components/transcriptions/assign-transcript/assign-transcript.component.html
  src/app/components/transcriptions/assign-transcript/assign-transcript.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-618

#624 DMP-1720 Wait before refreshing "Your transcripts" data
  src/app/components/transcriptions/transcriptions.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-624

#626 DMP-1738-Transcript-Requests
  src/app/components/common/data-table/data-table.component.spec.ts
  src/app/components/common/data-table/data-table.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-626

#619 DMP-1243: Assign transcript request, response and redirect
  cypress/e2e/functional/transcript-requests-spec.cy.js
  darts-api-stub/transcriptions/transcriptions.js
  src/app/components/transcriptions/assign-transcript/assign-transcript.component.html
  src/app/components/transcriptions/assign-transcript/assign-transcript.component.spec.ts
  src/app/components/transcriptions/assign-transcript/assign-transcript.component.ts
  src/app/components/transcriptions/view-transcript/view-transcript.component.html
  src/app/components/your-work/your-work.component.spec.ts
  src/app/components/your-work/your-work.component.ts
  src/app/services/transcription/transcription.service.spec.ts
  src/app/services/transcription/transcription.service.ts
  src/app/types/work-request.interface.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-619

#625 DMP-1566 - changed ids to use full id name.
  darts-api-stub/cases/case.js
  darts-api-stub/hearings/hearings.js
  darts-api-stub/transcriptions/transcriptions.js
  src/app/components/case/case.component.spec.ts
  src/app/components/hearing/hearing.component.spec.ts
  src/app/components/hearing/request-transcript/request-transcript-confirmation/request-transcript-confirmation.component.spec.ts
  src/app/components/hearing/request-transcript/request-transcript-confirmation/request-transcript-confirmation.component.ts
  src/app/components/hearing/request-transcript/request-transcript.component.html
  src/app/components/hearing/request-transcript/request-transcript.component.spec.ts
  src/app/components/hearing/request-transcript/request-transcript.component.ts
  src/app/services/case/case.service.spec.ts
  src/app/services/mapping/mapping.service.ts
  src/app/services/transcription/transcription.service.spec.ts
  src/app/types/transcript.interface.ts
  src/app/types/transcription-request.interface.ts
  src/app/types/transcription-type.interface.ts
  src/app/types/transcription-urgency.interface.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-625

#629 DMP-1765
  src/app/components/transcriptions/assign-transcript/assign-transcript.component.html
  src/app/components/transcriptions/assign-transcript/assign-transcript.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-629

#636 Hide nav on forbidden error screen
  src/app/components/error/forbidden/forbidden.component.spec.ts
  src/app/components/error/forbidden/forbidden.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-636

#631 DMP-1011 - Submit Approve/Reject transcript request
  src/app/components/transcriptions/approve-transcript/approve-transcript-buttons/approve-transcript-buttons.component.html
  src/app/components/transcriptions/approve-transcript/approve-transcript-buttons/approve-transcript-buttons.component.spec.ts
  src/app/components/transcriptions/approve-transcript/approve-transcript-buttons/approve-transcript-buttons.component.ts
  src/app/components/transcriptions/approve-transcript/approve-transcript.component.html
  src/app/components/transcriptions/approve-transcript/approve-transcript.component.ts
  src/app/services/transcription/transcription.service.spec.ts
  src/app/services/transcription/transcription.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-631

#638 DMP-871: Download Transcript
  cypress/e2e/functional/upload-transcript.cy.js
  cypress/e2e/functional/view-transcript.cy.js
  darts-api-stub/cases/case.js
  darts-api-stub/hearings/hearings.js
  darts-api-stub/transcriptions/download/TestDoc.docx
  darts-api-stub/transcriptions/transcriptions.js
  src/app/components/audios/audio-view/audio-view.component.spec.ts
  src/app/components/audios/audio-view/audio-view.component.ts
  src/app/components/case/case.component.spec.ts
  src/app/components/hearing/hearing.component.spec.ts
  src/app/components/transcriptions/view-transcript/view-transcript.component.html
  src/app/components/transcriptions/view-transcript/view-transcript.component.spec.ts
  src/app/components/transcriptions/view-transcript/view-transcript.component.ts
  src/app/services/file-download/file-download.service.spec.ts
  src/app/services/file-download/file-download.service.ts
  src/app/services/transcription/transcription.service.spec.ts
  src/app/services/transcription/transcription.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-638

#643 DMP-1024 - Multiple users tried to approve a request at the same time.
  cypress/e2e/functional/your-transcripts-spec.cy.js
  darts-api-stub/transcriptions/transcriptions.js
  src/app/components/transcriptions/approve-transcript/approve-transcript.component.html
  src/app/components/transcriptions/approve-transcript/approve-transcript.component.spec.ts
  src/app/components/transcriptions/approve-transcript/approve-transcript.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-643

#648 DMP-1815 - Error message - Neither Approve/Reject selected on request approval
  src/app/components/transcriptions/approve-transcript/approve-transcript-buttons/approve-transcript-buttons.component.spec.ts
  src/app/components/transcriptions/approve-transcript/approve-transcript-buttons/approve-transcript-buttons.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-648

#657 DMP-1773 Bug - Login b2c screen input errors
  server/assets/javascripts/errors.js
  server/assets/javascripts/login.js
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-657

#656 DMP-1668: Update the Hearing Details screen - Events and audio tab
  cypress/e2e/functional/request-audio-spec.cy.js
  src/app/components/common/audio-player/audio-player.component.html
  src/app/components/common/audio-player/audio-player.component.scss
  src/app/components/common/audio-player/audio-player.component.spec.ts
  src/app/components/common/audio-player/audio-player.component.ts
  src/app/components/common/data-table/data-table.component.html
  src/app/components/common/data-table/data-table.component.scss
  src/app/components/hearing/events-and-audio/events-and-audio.component.html
  src/app/components/hearing/events-and-audio/events-and-audio.component.scss
  src/app/components/hearing/events-and-audio/events-and-audio.component.spec.ts
  src/app/components/hearing/events-and-audio/events-and-audio.component.ts
  src/app/types/data-table-column.interface.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-656

#658 DMP-1773 Login b2c bug
  server/assets/javascripts/errors.js
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-658

#649 DMP-1746-Urgency-Sort
  darts-api-stub/transcriptions/transcriptions.js
  src/app/components/common/data-table/data-table.component.html
  src/app/components/common/data-table/data-table.component.spec.ts
  src/app/components/common/data-table/data-table.component.ts
  src/app/components/transcriptions/transcriptions.component.html
  src/app/components/transcriptions/transcriptions.component.spec.ts
  src/app/components/transcriptions/transcriptions.component.ts
  src/app/services/custom-sort/table-custom-sort-functions.service.spec.ts
  src/app/services/custom-sort/table-custom-sort-functions.service.ts
  src/app/services/transcription/transcription.service.spec.ts
  src/app/services/transcription/transcription.service.ts
  src/app/types/data-table-column.interface.ts
  src/app/types/index.ts
  src/app/types/transcription-urgency.interface.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-649

#647 DMP-1353 - 2 people assign a transcript request to themselves
  cypress/e2e/functional/transcript-requests-spec.cy.js
  darts-api-stub/transcriptions/transcriptions.js
  src/app/components/error/conflict/conflict.component.html
  src/app/components/error/conflict/conflict.component.scss
  src/app/components/error/conflict/conflict.component.spec.ts
  src/app/components/error/conflict/conflict.component.ts
  src/app/components/transcriptions/approve-transcript/approve-transcript.component.html
  src/app/components/transcriptions/approve-transcript/approve-transcript.component.ts
  src/app/components/transcriptions/assign-transcript/assign-transcript.component.html
  src/app/components/transcriptions/assign-transcript/assign-transcript.component.spec.ts
  src/app/components/transcriptions/assign-transcript/assign-transcript.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-647

#662 DMP-1746-Priority-Order-Sort
  darts-api-stub/transcriptions/transcriptions.js
  src/app/services/custom-sort/table-custom-sort-functions.service.spec.ts
  src/app/services/custom-sort/table-custom-sort-functions.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-662

#663 DMP-1773 B2C login errors
  server/assets/javascripts/errors.js
  server/assets/javascripts/login.js
  server/views/azuread-b2c-login.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-663

#664 DMP-1773 b2c
  server/assets/javascripts/errors.js
  server/assets/javascripts/login.js
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-664

#665 DMP-1746: Add urgency sort to required tables
  src/app/components/transcriptions/transcription-requests/transcription-requests.component.html
  src/app/components/transcriptions/transcription-requests/transcription-requests.component.ts
  src/app/components/transcriptions/transcriptions.component.html
  src/app/components/transcriptions/transcriptions.component.spec.ts
  src/app/components/transcriptions/transcriptions.component.ts
  src/app/components/your-work/your-work.component.html
  src/app/components/your-work/your-work.component.spec.ts
  src/app/components/your-work/your-work.component.ts
  src/app/constants/transcription-columns.ts
  src/app/services/sort/sort.service.spec.ts
  src/app/services/sort/sort.service.ts
  src/app/services/transcription/transcription.service.spec.ts
  src/app/services/transcription/transcription.service.ts
  src/app/types/user-transcription-request.interface.ts
  src/app/types/work-request.interface.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-665

#666 DMP-1865 hearing date bug on view transcript
  cypress/e2e/functional/transcript-requests-spec.cy.js
  darts-api-stub/transcriptions/transcriptions.js
  src/app/services/transcription/transcription.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-666

#671 Add missing govuk-links to a tags, override visited state
  src/app/components/audios/audios.component.html
  src/app/components/case/hearing-results/hearing-results.component.html
  src/app/components/hearing/hearing.component.html
  src/app/components/search/results/results.component.html
  src/app/components/transcriptions/transcription-requests/transcription-requests.component.html
  src/app/components/transcriptions/transcriptions.component.html
  src/app/components/your-work/your-work.component.html
  src/styles.scss
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-671

#669 DMP-1773 B2C login errors
  server/assets/javascripts/errors.js
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-669

#672 DMP-1837 & 1838
  src/app/components/transcriptions/approve-transcript/approve-transcript-buttons/approve-transcript-buttons.component.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-672

#650 DMP-1718: Refactor your audio to support media files new API response
  cypress/e2e/functional/error-spec.cy.js
  cypress/e2e/functional/your-audio-spec.cy.js
  darts-api-stub/audios/audio-requests.js
  darts-api-stub/hearings/hearings.js
  src/app/components/audios/audio-view/audio-view.component.html
  src/app/components/audios/audio-view/audio-view.component.spec.ts
  src/app/components/audios/audio-view/audio-view.component.ts
  src/app/components/audios/audios.component.html
  src/app/components/audios/audios.component.spec.ts
  src/app/components/audios/audios.component.ts
  src/app/components/hearing/hearing.component.spec.ts
  src/app/components/hearing/hearing.component.ts
  src/app/components/hearing/order-confirmation/order-confirmation.component.spec.ts
  src/app/components/hearing/order-confirmation/order-confirmation.component.ts
  src/app/components/hearing/request-playback-audio/request-playback-audio.component.ts
  src/app/services/audio-request/audio-request.service.spec.ts
  src/app/services/audio-request/audio-request.service.ts
  src/app/services/hearing/hearing.service.spec.ts
  src/app/services/hearing/hearing.service.ts
  src/app/types/audio-request-row.interface.ts
  src/app/types/index.ts
  src/app/types/post-audio-request.interface.ts
  src/app/types/post-audio-response.interface.ts
  src/app/types/requested-media.interface.ts
  src/app/types/user-audio-request-row.interface.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-650

#678 DMP-1806: Breadcrumb on approval screen
  src/app/components/transcriptions/approve-transcript/approve-transcript.component.html
  src/app/components/transcriptions/approve-transcript/approve-transcript.component.spec.ts
  src/app/components/transcriptions/approve-transcript/approve-transcript.component.ts
  src/app/services/transcription/transcription.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-678

#680 DMP-1925 Infinite loading bug
  src/app/components/search/search.component.spec.ts
  src/app/components/search/search.component.ts
  src/app/services/case/case.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-680

#681 DMP-1568: Audio player error messages
  cypress/e2e/functional/request-audio-spec.cy.js
  darts-api-stub/audios/index.js
  src/app/components/audios/audio-view/audio-view.component.spec.ts
  src/app/components/common/audio-player/audio-player.component.html
  src/app/components/common/audio-player/audio-player.component.spec.ts
  src/app/components/common/audio-player/audio-player.component.ts
  src/app/services/audio-request/audio-request.service.spec.ts
  src/app/services/audio-request/audio-request.service.ts
  src/app/services/error/error-message.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-681
