Repository hmcts/darts-portal, pull requests merged in 2023-05, with the labels that each got.

#30 DMP-72 Functional tests
  cypress/e2e/functional/functional-spec.cy.js
  cypress/e2e/smoke/smoke-spec.cy.js
  package.json
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-30

#38 [DMP-166] Fixes for using App insights key from the keyvault
  .pnp.cjs
  .yarn/cache/@hmcts-properties-volume-npm-0.0.14-6d0ff04d5a-3859effd7c.zip
  .yarn/cache/@types-config-npm-3.3.0-bdb6fd80cb-d9485041cf.zip
  .yarn/cache/config-npm-3.3.9-7e0be6fe2e-2c29e40be2.zip
  .yarn/cache/path-npm-0.12.7-bddabe2e86-5dedb71e78.zip
  .yarn/cache/process-npm-0.11.10-aeb3b641ae-bfcce49814.zip
  .yarn/cache/util-npm-0.10.4-7c577db41a-913f9a90d0.zip
  charts/darts-portal/Chart.yaml
  charts/darts-portal/values.dev.template.yaml
  charts/darts-portal/values.stg.template.yaml
  charts/darts-portal/values.yaml
  config/custom-environment-variables.json
  config/default.json
  pa11y/pa11y.ts
  package.json
  server/app-config.ts
  server/config.ts
  server/controllers/api.ts
  server/controllers/app.ts
  server/index.ts
  yarn.lock
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-38

#39 Adding .nvmrc file
  .nvmrc
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-39

#47 Adding POC login template for Azure AD to consume
  .pnp.cjs
  .yarn/cache/@types-nunjucks-npm-3.2.2-23e29b7301-e0fdc68f01.zip
  .yarn/cache/a-sync-waterfall-npm-1.0.1-f6b6b49568-534948b50d.zip
  .yarn/cache/commander-npm-5.1.0-7e939e7832-0b7fec1712.zip
  .yarn/cache/nunjucks-npm-3.2.4-c2cdc53bf5-8b902a9deb.zip
  nodemon.json
  package.json
  server/controllers/auth.ts
  server/routes.ts
  server/server.ts
  server/views/azuread-login.html
  yarn.lock
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-47

#48 Fixing up HTML as expected by Azure AD
  server/controllers/auth.ts
  server/views/azuread-login.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-48

#50 POC azure ad login2
  charts/darts-portal/Chart.yaml
  charts/darts-portal/values.yaml
  config/custom-environment-variables.json
  config/default.json
  server/controllers/auth.ts
  server/views/azuread-login.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-50

#51 Amending page name and prevent caching
  server/controllers/auth.ts
  server/views/azuread-b2c-login.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-51

#49 DTSPO-13810 reschedule nightlybuilds to start at 8am
  Jenkinsfile_nightly
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-49
