Repository hmcts/darts-portal, pull requests merged in 2023-11, with the labels that each got.

#482 DMP-770 Audio View - Download permissions, error messages
  cypress/e2e/functional/your-audio-spec.cy.js
  darts-api-stub/audios/audios.js
  src/app/components/audios/audio-view/audio-view.component.html
  src/app/components/audios/audio-view/audio-view.component.spec.ts
  src/app/components/audios/audio-view/audio-view.component.ts
  src/app/interceptors/error/error.interceptor.spec.ts
  src/app/services/audio-request/audio-request.service.spec.ts
  src/app/services/audio-request/audio-request.service.ts
  src/app/services/error/error-message.service.ts
  yarn.lock
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-482

#470 DMP-731: Playback audio screen
  cypress/e2e/functional/your-audio-spec.cy.js
  darts-api-stub/audios/audios.js
  darts-api-stub/audios/index.js
  darts-api-stub/hearings/hearings.js
  src/app/components/audios/audio-view/audio-view.component.html
  src/app/components/audios/audio-view/audio-view.component.scss
  src/app/components/audios/audio-view/audio-view.component.spec.ts
  src/app/components/audios/audio-view/audio-view.component.ts
  src/app/components/audios/audios.component.html
  src/app/components/audios/audios.component.spec.ts
  src/app/components/audios/audios.component.ts
  src/app/components/case/hearing-results/hearing-results.component.html
  src/app/components/case/hearing-results/hearing-results.component.ts
  src/app/components/common/audio-player/audio-player.component.html
  src/app/components/common/audio-player/audio-player.component.scss
  src/app/components/common/audio-player/audio-player.component.spec.ts
  src/app/components/common/audio-player/audio-player.component.ts
  src/app/components/common/data-table/data-table.component.scss
  src/app/components/common/data-table/data-table.component.spec.ts
  src/app/components/common/data-table/data-table.component.ts
  src/app/components/common/play-button/play-button.component.html
  src/app/components/common/play-button/play-button.component.scss
  src/app/components/common/play-button/play-button.component.spec.ts
  src/app/components/common/play-button/play-button.component.ts
  src/app/components/hearing/events-and-audio/events-and-audio.component.html
  src/app/components/hearing/events-and-audio/events-and-audio.component.ts
  src/app/components/layout/header/header.component.spec.ts
  src/app/components/search/results/results.component.ts
  src/app/components/search/search.component.html
  src/app/directives/table-row-template.directive.ts
  src/app/services/audio-request/audio-request.service.spec.ts
  src/app/services/audio-request/audio-request.service.ts
  src/app/types/case-row.interface.ts
  src/app/types/data-table-row.interface.ts
  src/app/types/hearing-audio-event.interface.ts
  src/app/types/hearing-event-row.interface.ts
  src/app/types/hearing-row.interface.ts
  src/app/types/index.ts
  src/app/types/transcripts-row.interface.ts
  src/app/types/user-audio-request-row.interface.ts
  src/app/types/user-audio-request.interface.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-470

#487 Temporary ignore failing FT statements
  cypress/e2e/functional/your-audio-spec.cy.js
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-487

#489 DM-1468 Fixing accessibility issue with empty table headers
  src/app/components/common/data-table/data-table.component.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-489

#488 DMP-892-Request-Transcript-Request-Type
  cypress/e2e/functional/request-transcript.cy.js
  darts-api-stub/index.js
  darts-api-stub/transcriptions/transcriptions.js
  src/app/app.routes.ts
  src/app/components/common/tabs/tabs.component.ts
  src/app/components/common/validation-error-summary/validation-error-summary.component.html
  src/app/components/common/validation-error-summary/validation-error-summary.component.scss
  src/app/components/common/validation-error-summary/validation-error-summary.component.spec.ts
  src/app/components/common/validation-error-summary/validation-error-summary.component.ts
  src/app/components/hearing/hearing.component.html
  src/app/components/hearing/hearing.component.spec.ts
  src/app/components/hearing/hearing.component.ts
  src/app/components/hearing/request-transcript/request-transcript.component.html
  src/app/components/hearing/request-transcript/request-transcript.component.scss
  src/app/components/hearing/request-transcript/request-transcript.component.spec.ts
  src/app/components/hearing/request-transcript/request-transcript.component.ts
  src/app/services/header/header.service.ts
  src/app/services/transcription/transcription.service.spec.ts
  src/app/services/transcription/transcription.service.ts
  src/app/types/index.ts
  src/app/types/transcription-type.interface.ts
  src/app/types/transcription-urgency.interface.ts
  src/main.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-488

#494 DMP-1383 - Inject user_id header for all DARTS API requests
  server/controllers/api.ts
  src/app/services/audio-request/audio-request.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-494

#490 DMP-917: Transcription Request Journey - Specific times and events
  cypress/e2e/functional/request-transcript.cy.js
  src/app/components/common/data-table/data-table.component.html
  src/app/components/hearing/request-transcript/request-times/request-times.component.html
  src/app/components/hearing/request-transcript/request-times/request-times.component.scss
  src/app/components/hearing/request-transcript/request-times/request-times.component.spec.ts
  src/app/components/hearing/request-transcript/request-times/request-times.component.ts
  src/app/components/hearing/request-transcript/request-transcript.component.html
  src/app/components/hearing/request-transcript/request-transcript.component.scss
  src/app/components/hearing/request-transcript/request-transcript.component.spec.ts
  src/app/components/hearing/request-transcript/request-transcript.component.ts
  src/app/services/transcription/transcription.service.spec.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-490

#495 DMP-934: Confirm transcript request
  src/app/components/hearing/request-transcript/request-times/request-times.component.html
  src/app/components/hearing/request-transcript/request-times/request-times.component.ts
  src/app/components/hearing/request-transcript/request-transcript-confirmation/request-transcript-confirmation.component.html
  src/app/components/hearing/request-transcript/request-transcript-confirmation/request-transcript-confirmation.component.scss
  src/app/components/hearing/request-transcript/request-transcript-confirmation/request-transcript-confirmation.component.spec.ts
  src/app/components/hearing/request-transcript/request-transcript-confirmation/request-transcript-confirmation.component.ts
  src/app/components/hearing/request-transcript/request-transcript.component.html
  src/app/components/hearing/request-transcript/request-transcript.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-495

#496 DMP-1012: Transcript request success screen
  cypress/e2e/functional/request-transcript.cy.js
  darts-api-stub/transcriptions/transcriptions.js
  src/app/components/hearing/request-transcript/request-times/request-times.component.html
  src/app/components/hearing/request-transcript/request-transcript-confirmation/request-transcript-confirmation.component.spec.ts
  src/app/components/hearing/request-transcript/request-transcript-confirmation/request-transcript-confirmation.component.ts
  src/app/components/hearing/request-transcript/request-transcript-success/request-transcript-success.component.html
  src/app/components/hearing/request-transcript/request-transcript-success/request-transcript-success.component.scss
  src/app/components/hearing/request-transcript/request-transcript-success/request-transcript-success.component.spec.ts
  src/app/components/hearing/request-transcript/request-transcript-success/request-transcript-success.component.ts
  src/app/components/hearing/request-transcript/request-transcript.component.html
  src/app/components/hearing/request-transcript/request-transcript.component.spec.ts
  src/app/components/hearing/request-transcript/request-transcript.component.ts
  src/app/services/transcription/transcription.service.spec.ts
  src/app/services/transcription/transcription.service.ts
  src/app/types/index.ts
  src/app/types/transcription-request.interface.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-496

#505 DMP-1513 Fixing accessibility issue with "Your audio" count
  src/app/components/layout/header/header.component.html
  src/app/components/layout/header/header.component.spec.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-505

#506 DMP-1528 Fixing tab order issue with request transcription cancel buttons
  src/app/components/hearing/request-transcript/request-times/request-times.component.html
  src/app/components/hearing/request-transcript/request-transcript-confirmation/request-transcript-confirmation.component.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-506

#509 Removing audio streaming testing changes
  config/custom-environment-variables.json
  config/default.json
  config/development.json
  server/controllers/api.ts
  server/middleware/session.ts
  server/routes.ts
  src/app/components/hearing/events-and-audio/events-and-audio.component.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-509

#508 Portal - Validation Error Summary Component
  src/app/components/audios/audio-view/audio-view.component.html
  src/app/components/audios/audio-view/audio-view.component.ts
  src/app/components/hearing/hearing.component.html
  src/app/components/hearing/hearing.component.ts
  src/app/components/login/login.component.html
  src/app/components/login/login.component.ts
  src/app/components/search/search.component.html
  src/app/components/search/search.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-508

#507 Introducing axe-core to cypress for accessibility standards
  README.md
  cypress/e2e/functional/auth-spec.cy.js
  cypress/e2e/functional/case-file-spec.cy.js
  cypress/e2e/functional/case-search-spec.cy.js
  cypress/e2e/functional/commands.js
  cypress/e2e/functional/error-spec.cy.js
  cypress/e2e/functional/hearing-transcripts-spec.cy.js
  cypress/e2e/functional/request-audio-spec.cy.js
  cypress/e2e/functional/request-transcript.cy.js
  cypress/e2e/functional/your-audio-spec.cy.js
  cypress/e2e/functional/your-transcripts-spec.cy.js
  pa11y/config.ts
  pa11y/pa11y.ts
  pa11y/tsconfig.json
  package.json
  yarn.lock
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-507

#518 DMP-1545: Set paging limit to 15 for request transcript journey
  src/app/components/hearing/request-transcript/request-times/request-times.component.html
  src/app/components/hearing/request-transcript/request-transcript.component.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-518

#521 DMP-872 - No audio available for transcript request
  src/app/components/hearing/request-transcript/request-transcript.component.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-521

#500 Change download url based on request type
  darts-api-stub/audios/audios.js
  src/app/components/audios/audio-view/audio-view.component.spec.ts
  src/app/components/audios/audio-view/audio-view.component.ts
  src/app/services/audio-request/audio-request.service.spec.ts
  src/app/services/audio-request/audio-request.service.ts
  src/app/types/user-audio-request-row.interface.ts
  yarn-audit-known-issues
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-500

#513 DMP-1408: Upgrade to Angular 17
  angular.json
  package.json
  src/app/components/common/tabs/tabs.component.ts
  src/app/components/hearing/request-transcript/request-transcript.component.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-513

#522 DMP-925 Duplicated transcription
  cypress/e2e/functional/request-transcript-spec.cy.js
  darts-api-stub/transcriptions/transcriptions.js
  src/app/components/hearing/request-transcript/request-transcript-exists/request-transcript-exists.component.html
  src/app/components/hearing/request-transcript/request-transcript-exists/request-transcript-exists.component.scss
  src/app/components/hearing/request-transcript/request-transcript-exists/request-transcript-exists.component.spec.ts
  src/app/components/hearing/request-transcript/request-transcript-exists/request-transcript-exists.component.ts
  src/app/components/hearing/request-transcript/request-transcript.component.html
  src/app/components/hearing/request-transcript/request-transcript.component.ts
  src/app/components/search/search-error/search-error.component.html
  src/app/components/search/search-error/search-error.component.spec.ts
  src/app/components/search/search.component.spec.ts
  src/app/components/search/search.component.ts
  src/app/services/error/error-message.service.ts
  src/app/types/error-message.interface.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-522

#512 DMP-868-View-Transcript-Screen
  cypress/e2e/functional/view-transcript.cy.js
  darts-api-stub/transcriptions/transcriptions.js
  package.json
  src/app/app.routes.ts
  src/app/components/case/hearing-results/hearing-results.component.html
  src/app/components/hearing/hearing.component.html
  src/app/components/hearing/request-transcript/request-transcript-exists/request-transcript-exists.component.html
  src/app/components/transcriptions/view-transcript/view-transcript.component.html
  src/app/components/transcriptions/view-transcript/view-transcript.component.scss
  src/app/components/transcriptions/view-transcript/view-transcript.component.spec.ts
  src/app/components/transcriptions/view-transcript/view-transcript.component.ts
  src/app/services/mapping/mapping.service.ts
  src/app/services/transcription/transcription.service.spec.ts
  src/app/services/transcription/transcription.service.ts
  src/app/types/index.ts
  src/app/types/transcription-details.interface.ts
  src/app/types/transcripts-row.interface.ts
  yarn.lock
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-512

#530 DMP-1479 Global error handling
  src/app/app.routes.ts
  src/app/components/case/case.component.html
  src/app/components/case/case.component.ts
  src/app/components/common/not-found/not-found.component.html
  src/app/components/error/forbidden/forbidden.component.html
  src/app/components/error/forbidden/forbidden.component.scss
  src/app/components/error/forbidden/forbidden.component.spec.ts
  src/app/components/error/forbidden/forbidden.component.ts
  src/app/components/error/not-found/not-found.component.html
  src/app/components/error/not-found/not-found.component.scss
  src/app/components/error/not-found/not-found.component.spec.ts
  src/app/components/error/not-found/not-found.component.ts
  src/app/components/search/search-error/search-error.component.spec.ts
  src/app/components/search/search.component.spec.ts
  src/app/services/error/error-message.service.spec.ts
  src/app/services/error/error-message.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-530

#525 DMP-1025: Your Transcripts
  cypress/e2e/functional/your-transcripts-spec.cy.js
  darts-api-stub/transcriptions/transcriptions.js
  jest.config.ts
  src/app/components/case/hearing-results/hearing-results.component.html
  src/app/components/case/hearing-results/hearing-results.component.ts
  src/app/components/transcriptions/transcriptions.component.html
  src/app/components/transcriptions/transcriptions.component.scss
  src/app/components/transcriptions/transcriptions.component.spec.ts
  src/app/components/transcriptions/transcriptions.component.ts
  src/app/constants/transcript-status-class-map.ts
  src/app/services/transcription/transcription.service.ts
  src/app/types/index.ts
  src/app/types/user-transcription-request-row.interface.ts
  src/app/types/user-transcription-request.interface.ts
  tsconfig.json
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-525

#544 DMP-1484 Preview audio player error message
  cypress/e2e/functional/request-audio-spec.cy.js
  darts-api-stub/audios/audio-requests.js
  darts-api-stub/audios/index.js
  darts-api-stub/index.js
  src/app/components/common/audio-player/audio-player.component.html
  src/app/components/common/audio-player/audio-player.component.spec.ts
  src/app/components/common/audio-player/audio-player.component.ts
  src/app/services/audio-request/audio-request.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-544

#545 DMP-1578 Duplicated transcription ID bug, view duplicated transcription link
  cypress/e2e/functional/request-transcript-spec.cy.js
  darts-api-stub/transcriptions/transcriptions.js
  src/app/components/hearing/request-transcript/request-transcript.component.html
  src/app/types/error-message.interface.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-545

#546 DMP-1511 - Error - 403 - No permission at courthouse for download audio request
  cypress/e2e/functional/request-audio-spec.cy.js
  darts-api-stub/audios/audio-requests.js
  src/app/components/error/forbidden/forbidden.component.html
  src/app/components/error/forbidden/forbidden.component.ts
  src/app/components/hearing/hearing.component.html
  src/app/components/hearing/hearing.component.spec.ts
  src/app/components/hearing/hearing.component.ts
  src/app/components/hearing/order-confirmation/order-confirmation.component.html
  src/app/services/error/error-message.service.ts
  src/app/types/hearing-page-state.type.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-546

#552 DMP-1588 accessibility update for skip to event play buttons
  src/app/components/audios/audio-view/audio-view.component.html
  yarn-audit-known-issues
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-552

#550 DMP-1453-Update-Azure-AD-B2C-References
  charts/darts-portal/Chart.yaml
  charts/darts-portal/values.yaml
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-550

#557 DMP-1610 Default name for transcription file, cypress updated
  cypress/e2e/functional/hearing-transcripts-spec.cy.js
  cypress/e2e/functional/view-transcript.cy.js
  darts-api-stub/hearings/hearings.js
  darts-api-stub/transcriptions/transcriptions.js
  src/app/services/transcription/transcription.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-557

#559 Your Audio - Prevent extra network call on load
  src/app/components/audios/audios.component.ts
  src/app/services/audio-request/audio-request.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-559

#535 Revert audio request download filename to 'output_filename . output_format'
  darts-api-stub/audios/audio-requests.js
  src/app/components/audios/audio-view/audio-view.component.spec.ts
  src/app/components/audios/audio-view/audio-view.component.ts
  src/app/services/audio-request/audio-request.service.spec.ts
  src/app/types/user-audio-request-row.interface.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-535

#565 DMP-1033-View-Transcript-Via-Your-Transcripts
  cypress/e2e/functional/view-transcript.cy.js
  darts-api-stub/hearings/hearings.js
  darts-api-stub/transcriptions/transcriptions.js
  src/app/app.routes.ts
  src/app/components/transcriptions/transcriptions.component.html
  src/app/components/transcriptions/view-transcript/view-transcript.component.html
  src/app/components/transcriptions/view-transcript/view-transcript.component.ts
  src/app/types/transcription-details.interface.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-565

#561 Add support for expired audio requests to delete audio stub
  darts-api-stub/audios/audio-requests.js
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-561

#566 DMP-1033-View-Transcript-Via-Your-Transcripts
  darts-api-stub/transcriptions/transcriptions.js
  src/app/components/transcriptions/view-transcript/view-transcript.component.html
  src/app/types/transcription-details.interface.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-566

#567 DMP-1589 Adding global skip link
  src/app/components/app.component.html
  src/app/components/app.component.spec.ts
  src/app/components/app.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-567

#570 Bug Fix: null requested_on error
  darts-api-stub/cases/case.js
  darts-api-stub/hearings/hearings.js
  src/app/services/case/case.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-570

#578 DMP-1646 Amending portal URL
  charts/darts-portal/Chart.yaml
  charts/darts-portal/values.stg.template.yaml
  charts/darts-portal/values.yaml
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-578

#577 Updated unit tests for transcription service
  src/app/services/transcription/transcription.service.spec.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-577

#579 DMP-1033-View-Transcript-Via-Your-Transcripts
  darts-api-stub/transcriptions/transcriptions.js
  src/app/components/transcriptions/view-transcript/view-transcript.component.html
  src/app/components/transcriptions/view-transcript/view-transcript.component.spec.ts
  src/app/components/transcriptions/view-transcript/view-transcript.component.ts
  src/app/types/transcription-details.interface.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-579

#584 DMP-1613: Allow only one audio to be previewed at a time
  src/app/components/common/audio-player/audio-player.component.ts
  src/app/components/hearing/events-and-audio/events-and-audio.component.html
  src/app/components/hearing/events-and-audio/events-and-audio.component.spec.ts
  src/app/components/hearing/events-and-audio/events-and-audio.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-584

#580 Enhancing stub users
  cypress/e2e/functional/auth-spec.cy.js
  cypress/e2e/functional/commands.js
  cypress/e2e/functional/request-audio-spec.cy.js
  cypress/e2e/functional/transcript-requests-spec.cy.js
  cypress/e2e/functional/view-transcript.cy.js
  cypress/e2e/functional/your-transcripts-spec.cy.js
  darts-api-stub/authentication/index.js
  darts-api-stub/authentication/internal.js
  darts-api-stub/index.js
  darts-api-stub/users.js
  darts-api-stub/views/external-login.ejs
  darts-api-stub/views/login.ejs
  darts-api-stub/views/logout.ejs
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-580

#585 DMP-1154 - Accessibility (WAVE) - View Hearing Screen - Empty Form Label
  src/app/components/common/data-table/data-table.component.html
  src/app/components/common/data-table/data-table.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-585

#590 UI components
  src/app/components/common/details-table/details-table.component.html
  src/app/components/common/details-table/details-table.component.scss
  src/app/components/common/details-table/details-table.component.spec.ts
  src/app/components/common/details-table/details-table.component.ts
  src/app/components/common/govuk-heading/govuk-heading.component.html
  src/app/components/common/govuk-heading/govuk-heading.component.scss
  src/app/components/common/govuk-heading/govuk-heading.component.spec.ts
  src/app/components/common/govuk-heading/govuk-heading.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-590

#591 DMP-1009 - Approve / Reject Transcription UI
  cypress/e2e/functional/commands.js
  cypress/e2e/functional/your-transcripts-spec.cy.js
  src/app/app.routes.spec.ts
  src/app/app.routes.ts
  src/app/auth/auth.guard.spec.ts
  src/app/auth/auth.guard.ts
  src/app/components/transcriptions/approve-transcript/approve-transcript-buttons/approve-transcript-buttons.component.html
  src/app/components/transcriptions/approve-transcript/approve-transcript-buttons/approve-transcript-buttons.component.scss
  src/app/components/transcriptions/approve-transcript/approve-transcript-buttons/approve-transcript-buttons.component.spec.ts
  src/app/components/transcriptions/approve-transcript/approve-transcript-buttons/approve-transcript-buttons.component.ts
  src/app/components/transcriptions/approve-transcript/approve-transcript.component.html
  src/app/components/transcriptions/approve-transcript/approve-transcript.component.scss
  src/app/components/transcriptions/approve-transcript/approve-transcript.component.spec.ts
  src/app/components/transcriptions/approve-transcript/approve-transcript.component.ts
  src/app/components/transcriptions/transcriptions.component.html
  src/app/components/transcriptions/view-transcript/view-transcript.component.html
  src/app/components/transcriptions/view-transcript/view-transcript.component.ts
  src/app/services/user/user.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-591

#592 Fixing some sonar issues
  cypress/e2e/functional/request-audio-spec.cy.js
  src/app/components/app.component.html
  src/app/components/app.component.spec.ts
  src/app/components/app.component.ts
  src/app/components/audios/audio-view/audio-view.component.html
  src/app/components/audios/audio-view/audio-view.component.ts
  src/app/components/common/courthouse/courthouse.component.ts
  src/app/components/common/data-table/data-table.component.html
  src/app/components/common/data-table/data-table.component.ts
  src/app/components/hearing/events-and-audio/events-and-audio.component.html
  src/app/components/hearing/request-transcript/request-transcript-confirmation/request-transcript-confirmation.component.ts
  src/app/components/hearing/request-transcript/request-transcript.component.ts
  src/app/components/layout/phase-banner/phase-banner.component.css
  src/app/components/layout/phase-banner/phase-banner.component.html
  src/app/components/layout/phase-banner/phase-banner.component.spec.ts
  src/app/components/layout/phase-banner/phase-banner.component.ts
  src/app/components/search/results/results.component.ts
  src/app/extensions/HttpBackendClient.ts
  src/app/pipes/join.ts
  src/assets/datepicker.scss
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-592

#593 DMP-1455 MFA B2C Changes
  server/assets/javascripts/mfa.js
  server/assets/stylesheets/mfa.css
  server/views/azuread-b2c-login.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-593

#594 DMP-1326: Upload Transcript
  cypress/e2e/functional/upload-transcript.cy.js
  darts-api-stub/transcriptions/transcriptions.js
  src/app/app.routes.ts
  src/app/components/common/details-table/details-table.component.html
  src/app/components/common/details-table/details-table.component.ts
  src/app/components/common/file-upload/file-upload.component.html
  src/app/components/common/file-upload/file-upload.component.scss
  src/app/components/common/file-upload/file-upload.component.spec.ts
  src/app/components/common/file-upload/file-upload.component.ts
  src/app/components/hearing/hearing.component.ts
  src/app/components/transcriptions/approve-transcript/approve-transcript.component.spec.ts
  src/app/components/transcriptions/approve-transcript/approve-transcript.component.ts
  src/app/components/transcriptions/view-transcript/view-transcript.component.html
  src/app/components/your-work/completed-transcript/completed-transcript.component.html
  src/app/components/your-work/completed-transcript/completed-transcript.component.scss
  src/app/components/your-work/completed-transcript/completed-transcript.component.spec.ts
  src/app/components/your-work/completed-transcript/completed-transcript.component.ts
  src/app/components/your-work/upload-transcript/upload-transcript.component.html
  src/app/components/your-work/upload-transcript/upload-transcript.component.scss
  src/app/components/your-work/upload-transcript/upload-transcript.component.spec.ts
  src/app/components/your-work/upload-transcript/upload-transcript.component.ts
  src/app/services/transcription/transcription.service.spec.ts
  src/app/services/transcription/transcription.service.ts
  src/app/types/transcription-details.interface.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-594

#596 DMP-1455 MFA B2C Changes
  server/assets/javascripts/mfa.js
  server/assets/stylesheets/mfa.css
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-596

#599 DMP-1455 MFA B2C changes
  server/assets/javascripts/mfa.js
  server/assets/stylesheets/mfa.css
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-599

#601 DMP-1455 MFA B2C
  server/assets/javascripts/mfa.js
  server/assets/stylesheets/login.css
  server/assets/stylesheets/mfa.css
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-601

#600 DMP-1685: Add JUDGE role to Your transcripts & some minor fixes
  cypress/e2e/functional/request-audio-spec.cy.js
  cypress/e2e/functional/view-transcript.cy.js
  cypress/e2e/functional/your-audio-spec.cy.js
  cypress/e2e/functional/your-transcripts-spec.cy.js
  darts-api-stub/roles.js
  darts-api-stub/users.js
  src/app/app.routes.ts
  src/app/components/audios/audio-view/audio-view.component.html
  src/app/components/audios/audios.component.html
  src/app/components/layout/header/header.component.html
  src/app/components/layout/header/header.component.spec.ts
  src/app/components/transcriptions/transcriptions.component.html
  src/app/components/transcriptions/transcriptions.component.spec.ts
  src/app/components/transcriptions/transcriptions.component.ts
  src/app/components/your-work/upload-transcript/upload-transcript.component.html
  src/app/components/your-work/upload-transcript/upload-transcript.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-600

#571 Fix empty transcript scenario for case screen
  cypress/e2e/functional/hearing-transcripts-spec.cy.js
  src/app/components/case/hearing-results/hearing-results.component.html
  src/app/components/common/data-table/data-table.component.html
  src/app/components/common/data-table/data-table.component.spec.ts
  src/app/components/common/data-table/data-table.component.ts
  src/app/components/hearing/hearing.component.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-571

#603 DMP-1455 MFA B2C
  server/assets/javascripts/mfa.js
  server/assets/stylesheets/mfa.css
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-603

#604 Remove allowed roles to enable to test
  src/app/app.routes.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-604

#605 DMP-1457 TOTP B2C
  server/assets/javascripts/errors.js
  server/assets/javascripts/mfa.js
  server/assets/javascripts/reset-password.js
  server/assets/stylesheets/mfa.css
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-605

#595 DMP-1255 - Transcriber's Your Work - To do Screen
  cypress/e2e/functional/your-work-spec.cy.js
  darts-api-stub/transcriptions/transcriptions.js
  src/app/components/common/tabs/tabs.component.html
  src/app/components/your-work/upload-transcript/upload-transcript.component.html
  src/app/components/your-work/your-work.component.html
  src/app/components/your-work/your-work.component.spec.ts
  src/app/components/your-work/your-work.component.ts
  src/app/directives/tab.directive.ts
  src/app/services/transcription/transcription.service.spec.ts
  src/app/services/transcription/transcription.service.ts
  src/app/types/index.ts
  src/app/types/work-request.interface.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-595
