Repository hmcts/darts-portal, pull requests merged in 2023-09, with the labels that each got.

#258 DMP-772: Add Pagination
  src/app/components/search/results/results.component.html
  src/app/components/search/results/results.component.spec.ts
  src/app/components/search/results/results.component.ts
  src/app/components/search/search.component.html
  src/app/components/shared/pagination/pagination.component.html
  src/app/components/shared/pagination/pagination.component.scss
  src/app/components/shared/pagination/pagination.component.spec.ts
  src/app/components/shared/pagination/pagination.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-258

#265 camel to snake changes in stub, front end refs, types
  darts-api-stub/case/case.js
  src/app/components/search/results/results.component.html
  src/app/components/search/results/results.component.spec.ts
  src/app/types/case.d.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-265

#262 DMP-557-Case-File-Screen
  darts-api-stub/case/case.js
  src/app/app.routes.ts
  src/app/components/case/case-file/case-file.component.html
  src/app/components/case/case-file/case-file.component.scss
  src/app/components/case/case-file/case-file.component.spec.ts
  src/app/components/case/case-file/case-file.component.ts
  src/app/components/case/case.component.html
  src/app/components/case/case.component.scss
  src/app/components/case/case.component.spec.ts
  src/app/components/case/case.component.ts
  src/app/components/case/hearing-results/hearing-results.component.html
  src/app/components/case/hearing-results/hearing-results.component.scss
  src/app/components/case/hearing-results/hearing-results.component.spec.ts
  src/app/components/case/hearing-results/hearing-results.component.ts
  src/app/components/search/results/results.component.html
  src/app/components/search/results/results.component.ts
  src/app/services/case/case.service.spec.ts
  src/app/services/case/case.service.ts
  src/app/types/case-file.d.ts
  src/app/types/hearing.d.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-262

#273 DMP-828 View Hearing Details
  src/app/app.routes.ts
  src/app/components/case/case-file/case-file.component.ts
  src/app/components/case/case.component.spec.ts
  src/app/components/case/case.component.ts
  src/app/components/case/hearing-results/hearing-results.component.html
  src/app/components/case/hearing-results/hearing-results.component.spec.ts
  src/app/components/case/hearing-results/hearing-results.component.ts
  src/app/components/hearing/hearing-file/hearing-file.component.html
  src/app/components/hearing/hearing-file/hearing-file.component.scss
  src/app/components/hearing/hearing-file/hearing-file.component.spec.ts
  src/app/components/hearing/hearing-file/hearing-file.component.ts
  src/app/components/hearing/hearing.component.html
  src/app/components/hearing/hearing.component.scss
  src/app/components/hearing/hearing.component.spec.ts
  src/app/components/hearing/hearing.component.ts
  src/app/components/search/results/results.component.ts
  src/app/services/case/case.service.spec.ts
  src/app/services/case/case.service.ts
  src/app/services/datetime/datetime.service.spec.ts
  src/app/services/datetime/datetime.service.ts
  src/app/types/case.d.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-273

#257 Subscribe updates
  src/app/components/search/search.component.ts
  src/app/interceptor/error/error.interceptor.spec.ts
  src/app/services/case/case.service.spec.ts
  yarn.lock
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-257

#261 DMP-875: Fix Error handling & AppInsights
  src/app/components/hearing/hearing.component.spec.ts
  src/app/components/search/search.component.spec.ts
  src/app/extensions/HttpBackendClient.ts
  src/app/interceptor/error/error.interceptor.spec.ts
  src/app/interceptor/error/error.interceptor.ts
  src/app/services/app-config/app-config.service.ts
  src/app/services/app-insights/app-insights.service.ts
  src/app/services/case/case.service.spec.ts
  src/app/services/case/case.service.ts
  src/app/services/error/error-handler.service.spec.ts
  src/app/services/error/error-handler.service.ts
  src/main.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-261

#239 Update README.md
  README.md
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-239

#270 DMP-658: Hearings Events and Audio
  darts-api-stub/case/case.js
  src/app/components/case/case-file/case-file.component.scss
  src/app/components/case/case.component.ts
  src/app/components/case/hearing-results/hearing-results.component.ts
  src/app/components/hearing/events-and-audio/events-and-audio.component.html
  src/app/components/hearing/events-and-audio/events-and-audio.component.scss
  src/app/components/hearing/events-and-audio/events-and-audio.component.spec.ts
  src/app/components/hearing/events-and-audio/events-and-audio.component.ts
  src/app/components/hearing/hearing-file/hearing-file.component.html
  src/app/components/hearing/hearing.component.html
  src/app/components/hearing/hearing.component.ts
  src/app/services/case/case.service.ts
  src/app/services/datetime/datetime.service.ts
  src/app/services/hearing/hearing.service.spec.ts
  src/app/services/hearing/hearing.service.ts
  src/app/types/enums.ts
  src/app/types/hearing-audio-event.d.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-270

#259 Fix pa11y issues
  pa11y/pa11y.ts
  src/app/components/login/login.component.html
  src/app/components/search/search.component.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-259

#274 Portal - Advanced Search - Specific date picker not setting date_to
  src/app/components/search/search.component.spec.ts
  src/app/components/search/search.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-274

#275 DMP-823: Hearings event log only view
  darts-api-stub/case/case.js
  src/app/components/hearing/events-and-audio/events-and-audio.component.html
  src/app/components/hearing/events-and-audio/events-and-audio.component.scss
  src/app/components/hearing/events-and-audio/events-and-audio.component.spec.ts
  src/app/components/hearing/events-and-audio/events-and-audio.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-275

#277 DMP-772: Fix pagination refresh bug
  src/app/components/search/results/results.component.spec.ts
  src/app/components/search/results/results.component.ts
  src/app/components/shared/pagination/pagination.component.html
  src/app/components/shared/pagination/pagination.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-277

#276 Functional testing structure
  cypress/e2e/functional/auth-spec.cy.js
  cypress/e2e/functional/case-search-spec.cy.js
  cypress/e2e/functional/commands.js
  cypress/e2e/functional/functional-spec.cy.js
  cypress/e2e/functional/my-audios-spec.cy.js
  cypress/e2e/functional/my-transcriptions-spec.cy.js
  darts-api-stub/index.js
  package.json
  scripts/start-app.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-276

#283 Fix audio API endpoint
  darts-api-stub/index.js
  src/app/services/hearing/hearing.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-283

#280 Fix whitespace on hearing screen
  src/app/components/hearing/hearing.component.scss
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-280

#287 Demo tweaks
  src/app/components/app.component.html
  src/app/components/case/case-file/case-file.component.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-287

#291 fix favicon
  src/index.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-291

#295 DMP-891: Text change 'Case number' to 'Case ID'
  src/app/components/search/results/results.component.html
  src/app/components/search/search.component.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-295

#293 DMP-890: Table column headers
  src/app/components/search/results/results.component.html
  src/styles.scss
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-293

#294 DMP-695-Request-Playback-Audio
  darts-api-stub/case/case.js
  pa11y/pa11y.ts
  src/app/components/hearing/events-and-audio/events-and-audio.component.html
  src/app/components/hearing/events-and-audio/events-and-audio.component.scss
  src/app/components/hearing/events-and-audio/events-and-audio.component.spec.ts
  src/app/components/hearing/events-and-audio/events-and-audio.component.ts
  src/app/components/hearing/hearing.component.html
  src/app/components/hearing/hearing.component.spec.ts
  src/app/components/hearing/hearing.component.ts
  src/app/components/hearing/request-playback-audio/request-playback-audio.component.html
  src/app/components/hearing/request-playback-audio/request-playback-audio.component.scss
  src/app/components/hearing/request-playback-audio/request-playback-audio.component.spec.ts
  src/app/components/hearing/request-playback-audio/request-playback-audio.component.ts
  src/app/components/hearing/request-playback-audio/time-input/time-input.component.html
  src/app/components/hearing/request-playback-audio/time-input/time-input.component.scss
  src/app/components/hearing/request-playback-audio/time-input/time-input.component.spec.ts
  src/app/components/hearing/request-playback-audio/time-input/time-input.component.ts
  src/app/services/datetime/datetime.service.spec.ts
  src/app/services/datetime/datetime.service.ts
  src/app/services/hearing/hearing.service.ts
  src/app/types/requestPlaybackAudioDTO.d.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-294

#303 DMP 880 updated url and stubbed
  darts-api-stub/hearings/hearings.js
  darts-api-stub/index.js
  src/app/services/hearing/hearing.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-303

#298 DMP-773: Case search results sortable columns
  src/app/components/search/results/results.component.html
  src/app/components/search/results/results.component.scss
  src/app/components/search/results/results.component.spec.ts
  src/app/components/search/results/results.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-298

#286 DMP-691: Search Validation Errors
  src/app/components/common/courthouse/courthouse.component.html
  src/app/components/common/courthouse/courthouse.component.spec.ts
  src/app/components/common/courthouse/courthouse.component.ts
  src/app/components/common/pagination/pagination.component.html
  src/app/components/common/pagination/pagination.component.scss
  src/app/components/common/pagination/pagination.component.spec.ts
  src/app/components/common/pagination/pagination.component.ts
  src/app/components/search/results/results.component.ts
  src/app/components/search/search.component.html
  src/app/components/search/search.component.scss
  src/app/components/search/search.component.spec.ts
  src/app/components/search/search.component.ts
  src/app/services/case/case.service.spec.ts
  src/app/services/case/case.service.ts
  src/app/types/search-form.interface.ts
  src/app/validators/future-date.validator.ts
  src/styles.scss
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-286

#302 DMP-950: Search validation / errors
  src/app/components/hearing/request-playback-audio/request-playback-audio.component.spec.ts
  src/app/components/search/results/results.component.html
  src/app/components/search/results/results.component.ts
  src/app/components/search/search.component.html
  src/app/components/search/search.component.spec.ts
  src/app/components/search/search.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-302

#309 Remove duplicate validation message for courthouse
  src/app/components/search/search.component.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-309

#311 DMP-691: Date validation bug fixes
  src/app/components/search/search.component.html
  src/app/components/search/search.component.spec.ts
  src/app/components/search/search.component.ts
  src/app/validators/future-date.validator.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-311

#314 DMP-1014: Text change for 'CASE_101' error
  src/app/components/search/results/results.component.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-314

#292 Add import aliases
  jest.config.ts
  src/app/auth/auth.guard.spec.ts
  src/app/auth/auth.guard.ts
  src/app/components/app.component.spec.ts
  src/app/components/app.component.ts
  src/app/components/case/case-file/case-file.component.spec.ts
  src/app/components/case/case-file/case-file.component.ts
  src/app/components/case/case.component.spec.ts
  src/app/components/case/case.component.ts
  src/app/components/case/hearing-results/hearing-results.component.spec.ts
  src/app/components/case/hearing-results/hearing-results.component.ts
  src/app/components/common/courthouse/courthouse.component.spec.ts
  src/app/components/common/courthouse/courthouse.component.ts
  src/app/components/hearing/events-and-audio/events-and-audio.component.spec.ts
  src/app/components/hearing/events-and-audio/events-and-audio.component.ts
  src/app/components/hearing/hearing-file/hearing-file.component.ts
  src/app/components/hearing/hearing.component.spec.ts
  src/app/components/hearing/hearing.component.ts
  src/app/components/hearing/request-playback-audio/request-playback-audio.component.ts
  src/app/components/layout/header/header.component.spec.ts
  src/app/components/layout/header/header.component.ts
  src/app/components/login/login.component.spec.ts
  src/app/components/login/login.component.ts
  src/app/components/search/results/results.component.spec.ts
  src/app/components/search/results/results.component.ts
  src/app/components/search/search.component.spec.ts
  src/app/components/search/search.component.ts
  src/app/interceptors/error/error.interceptor.spec.ts
  src/app/interceptors/error/error.interceptor.ts
  src/app/services/app-insights/app-insights.service.spec.ts
  src/app/services/app-insights/app-insights.service.ts
  src/app/services/case/case.service.spec.ts
  src/app/services/case/case.service.ts
  src/app/services/error/error-handler.service.spec.ts
  src/app/services/error/error-handler.service.ts
  src/app/services/hearing/hearing.service.ts
  src/app/types/case-file.ts
  src/app/types/case.d.ts
  src/app/types/case.ts
  src/app/types/courthouse.ts
  src/app/types/hearing-audio-event.ts
  src/app/types/hearing-state.ts
  src/app/types/hearing.ts
  src/app/types/index.ts
  src/app/types/requestPlaybackAudioDTO.ts
  src/main.ts
  tsconfig.json
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-292

#322 DMP-1029-Primary-Navigation-Show-and-Hide
  src/app/components/hearing/hearing.component.spec.ts
  src/app/components/hearing/hearing.component.ts
  src/app/components/layout/header/header.component.html
  src/app/components/layout/header/header.component.ts
  src/app/services/header/header.service.spec.ts
  src/app/services/header/header.service.ts
  src/app/types/hearing-state.d.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-322

#320 DMP-1016: Clear errors from search results on clear search
  src/app/components/search/search.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-320

#317 DMP-1026: Reset column sort on new search
  src/app/components/search/results/results.component.spec.ts
  src/app/components/search/results/results.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-317

#323 DMP-1032-link-mouseover/hover-styles
  src/styles.scss
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-323

#315 DMP-912 case search functional tests
  .gitignore
  Jenkinsfile_CNP
  cypress.config.js
  cypress/e2e/functional/case-search-spec.cy.js
  darts-api-stub/audios/index.js
  darts-api-stub/cases/case.js
  darts-api-stub/index.js
  package.json
  src/app/components/case/case-file/case-file.component.html
  src/app/components/case/case-file/case-file.component.ts
  src/app/components/common/courthouse/courthouse.component.html
  src/app/components/common/courthouse/courthouse.component.spec.ts
  src/app/components/common/courthouse/courthouse.component.ts
  src/app/components/hearing/hearing-file/hearing-file.component.html
  src/app/components/hearing/hearing-file/hearing-file.component.ts
  src/app/components/search/results/results.component.html
  src/app/components/search/search.component.html
  src/app/pipes/join.spec.ts
  src/app/pipes/join.ts
  yarn.lock
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-315

#324 DMP-685-Order-Confirmation-Screen
  darts-api-stub/audios/audios.js
  darts-api-stub/index.js
  src/app/components/case/case-file/case-file.component.html
  src/app/components/case/case-file/case-file.component.ts
  src/app/components/common/reporting-restriction/reporting-restriction.component.html
  src/app/components/common/reporting-restriction/reporting-restriction.component.scss
  src/app/components/common/reporting-restriction/reporting-restriction.component.spec.ts
  src/app/components/common/reporting-restriction/reporting-restriction.component.ts
  src/app/components/hearing/hearing-file/hearing-file.component.html
  src/app/components/hearing/hearing-file/hearing-file.component.ts
  src/app/components/hearing/hearing.component.html
  src/app/components/hearing/hearing.component.scss
  src/app/components/hearing/hearing.component.spec.ts
  src/app/components/hearing/hearing.component.ts
  src/app/components/hearing/order-confirmation/order-confirmation.component.html
  src/app/components/hearing/order-confirmation/order-confirmation.component.scss
  src/app/components/hearing/order-confirmation/order-confirmation.component.spec.ts
  src/app/components/hearing/order-confirmation/order-confirmation.component.ts
  src/app/components/hearing/request-playback-audio/request-playback-audio.component.spec.ts
  src/app/components/hearing/request-playback-audio/request-playback-audio.component.ts
  src/app/services/hearing/hearing.service.spec.ts
  src/app/services/hearing/hearing.service.ts
  src/app/types/hearing-state.d.ts
  src/app/types/responsePlaybackAudioDTO.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-324

#329 DMP-995/999/1000/1001 - accessibility changes
  server/assets/javascripts/login.js
  server/views/azuread-b2c-login.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-329

#334 DMP-1000 add aria-required to azure email input
  server/assets/javascripts/login.js
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-334

#331 Exposing user profile to angular
  darts-api-stub/authentication/external.js
  server/controllers/index.ts
  server/controllers/user.ts
  server/routes.ts
  server/types/classes/securityToken.ts
  server/types/classes/userState.ts
  src/app/components/search/search.component.ts
  src/app/services/app-config/app-config.service.ts
  src/app/services/user/user.service.spec.ts
  src/app/services/user/user.service.ts
  src/app/types/user-state.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-331

#335 DMP-1055-Email address for order confirmation screen
  src/app/components/hearing/hearing.component.html
  src/app/components/hearing/hearing.component.spec.ts
  src/app/components/hearing/hearing.component.ts
  src/app/components/hearing/order-confirmation/order-confirmation.component.html
  src/app/components/hearing/order-confirmation/order-confirmation.component.ts
  src/app/services/hearing/hearing.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-335

#338 DMP-992 added roles to radio labels login page
  src/app/components/login/login.component.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-338

#330 Rename Interfaces to follow Angular Style Guide
  src/app/components/case/case-file/case-file.component.ts
  src/app/components/case/case.component.spec.ts
  src/app/components/case/hearing-results/hearing-results.component.spec.ts
  src/app/components/case/hearing-results/hearing-results.component.ts
  src/app/components/common/courthouse/courthouse.component.spec.ts
  src/app/components/common/courthouse/courthouse.component.ts
  src/app/components/hearing/events-and-audio/events-and-audio.component.ts
  src/app/components/hearing/hearing-file/hearing-file.component.ts
  src/app/components/hearing/hearing.component.spec.ts
  src/app/components/hearing/hearing.component.ts
  src/app/components/hearing/order-confirmation/order-confirmation.component.spec.ts
  src/app/components/hearing/order-confirmation/order-confirmation.component.ts
  src/app/components/hearing/request-playback-audio/request-playback-audio.component.ts
  src/app/components/search/results/results.component.spec.ts
  src/app/components/search/results/results.component.ts
  src/app/components/search/search.component.spec.ts
  src/app/components/search/search.component.ts
  src/app/services/case/case.service.spec.ts
  src/app/services/case/case.service.ts
  src/app/services/hearing/hearing.service.spec.ts
  src/app/services/hearing/hearing.service.ts
  src/app/types/audio-request.interface.ts
  src/app/types/audio-response.interface.ts
  src/app/types/case-file.interface.ts
  src/app/types/case.interface.ts
  src/app/types/courthouse.interface.ts
  src/app/types/hearing-audio-event.interface.ts
  src/app/types/hearing-audio.interface.ts
  src/app/types/hearing-event.interface.ts
  src/app/types/hearing-page-state.type.ts
  src/app/types/hearing.interface.ts
  src/app/types/index.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-330

#347 DMP-992 accessibility radio role
  src/app/components/login/login.component.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-347

#348 Add no cache middleware to node / express
  server/server.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-348

#341 Remove angular material dependency
  angular.json
  package.json
  src/index.html
  yarn.lock
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-341

#355 Adding loading component
  src/app/components/common/loading/loading.component.html
  src/app/components/common/loading/loading.component.scss
  src/app/components/common/loading/loading.component.spec.ts
  src/app/components/common/loading/loading.component.ts
  src/app/components/hearing/hearing.component.html
  src/app/components/hearing/hearing.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-355

#343 Add 404 error page
  src/app/app.routes.spec.ts
  src/app/app.routes.ts
  src/app/components/common/not-found/not-found.component.html
  src/app/components/common/not-found/not-found.component.scss
  src/app/components/common/not-found/not-found.component.spec.ts
  src/app/components/common/not-found/not-found.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-343

#356 DMP-692: Audio preview (UI Only)
  src/app/components/common/audio-player/audio-player.component.html
  src/app/components/common/audio-player/audio-player.component.scss
  src/app/components/common/audio-player/audio-player.component.spec.ts
  src/app/components/common/audio-player/audio-player.component.ts
  src/app/components/hearing/events-and-audio/events-and-audio.component.html
  src/app/components/hearing/events-and-audio/events-and-audio.component.scss
  src/app/components/hearing/events-and-audio/events-and-audio.component.spec.ts
  src/app/components/hearing/events-and-audio/events-and-audio.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-356

#358 DMP-1015 Case search aria-label datepicker
  src/app/components/search/search.component.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-358

#342 Data Table Component
  src/app/components/case/case.component.spec.ts
  src/app/components/case/hearing-results/hearing-results.component.html
  src/app/components/case/hearing-results/hearing-results.component.spec.ts
  src/app/components/case/hearing-results/hearing-results.component.ts
  src/app/components/common/data-table/data-table.component.html
  src/app/components/common/data-table/data-table.component.scss
  src/app/components/common/data-table/data-table.component.spec.ts
  src/app/components/common/data-table/data-table.component.ts
  src/app/components/home/home.component.ts
  src/app/components/search/results/results.component.html
  src/app/components/search/results/results.component.spec.ts
  src/app/components/search/results/results.component.ts
  src/main.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-342

#361 DMP-992 radio login inputs, aria checked for label
  src/app/components/login/login.component.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-361

#360 DMP 860 changed My to your and fixed tests
  cypress/e2e/functional/my-audios-spec.cy.js
  cypress/e2e/functional/my-transcriptions-spec.cy.js
  cypress/e2e/functional/your-audio-spec.cy.js
  cypress/e2e/functional/your-transcripts-spec.cy.js
  src/app/components/audios/audios.component.html
  src/app/components/layout/header/header.component.html
  src/app/components/transcriptions/transcriptions.component.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-360
