Repository hmcts/darts-portal, pull requests merged in 2023-06, with the labels that each got.

#60 yarn-PnP fix (fixes imports and tslib issue)
  .yarn/sdks/eslint/package.json
  .yarn/sdks/prettier/package.json
  .yarn/sdks/typescript/lib/tsserver.js
  .yarn/sdks/typescript/lib/tsserverlibrary.js
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-60

#84 DMP-429 Page layout header update
  .pnp.cjs
  .yarn/cache/@angular-builders-custom-webpack-npm-16.0.0-85febefdce-6fcc13f76f.zip
  .yarn/cache/@angular-builders-dev-server-npm-7.3.3-d0c1733abd-91857a12ce.zip
  .yarn/cache/@angular-devkit-architect-npm-0.1601.0-a32b546957-64119cf304.zip
  .yarn/cache/@angular-devkit-core-npm-16.1.0-41ed2ebbf4-6f9719e7d0.zip
  .yarn/cache/webpack-merge-npm-5.9.0-9110e650de-64fe2c23aa.zip
  angular.json
  pa11y/pa11y.ts
  package.json
  src/app/components/layout/header/header.component.html
  src/styles.scss
  webpack.config.js
  yarn.lock
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-84

#87 DMP-430 Fixing auth callback request to DARTS API
  server/controllers/api.ts
  server/controllers/authentication.ts
  server/routes.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-87

#88 Fixes for Azure AD B2C login page template
  charts/darts-portal/Chart.yaml
  charts/darts-portal/values.dev.template.yaml
  charts/darts-portal/values.stg.template.yaml
  charts/darts-portal/values.yaml
  config/custom-environment-variables.json
  config/default.json
  package.json
  server/controllers/auth.ts
  server/views/azuread-b2c-login.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-88

#92 DARTS_PORTAL_HOSTNAME -> DARTS_PORTAL_URL
  charts/darts-portal/Chart.yaml
  charts/darts-portal/values.dev.template.yaml
  charts/darts-portal/values.stg.template.yaml
  charts/darts-portal/values.yaml
  config/custom-environment-variables.json
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-92

#93 Setting CORS headers on Azure AD B2C login pages
  server/server.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-93

#94 Auth fix and api stub
  .pnp.cjs
  darts-api-stub/authentication/external.js
  darts-api-stub/index.js
  darts-api-stub/views/external-login.ejs
  package.json
  server/controllers/authentication.ts
  yarn.lock
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-94

#98 Adding timestamp to angular session check
  .pnp.cjs
  Dockerfile
  angular.json
  package.json
  server/controllers/authentication.ts
  src/app/services/auth/auth.service.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-98

#100 DMP-433 unauthenticated route preservation and redirect after successful authentication
  src/app/auth/auth.guard.ts
  src/app/components/home/home.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-100

#103 More authentication fixes
  src/app/auth/auth.guard.spec.ts
  src/app/auth/auth.guard.ts
  src/app/components/layout/header/header.component.spec.ts
  src/app/components/layout/header/header.component.ts
  src/app/components/login/login.component.spec.ts
  src/app/components/login/login.component.ts
  src/app/services/auth/auth.service.spec.ts
  src/app/services/auth/auth.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-103

#101 Dmp 361 external login page
  server/views/azuread-b2c-login.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-101

#104 Adding Jenkinsfile_parameterized, for deploy to sandbox
  Jenkinsfile_parameterized
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-104

#105 Cookie debugging
  .pnp.cjs
  .yarn/cache/@types-cookie-parser-npm-1.4.3-4bda65954a-f390f3af1b.zip
  .yarn/cache/cookie-npm-0.4.1-cc5e2ebb42-bd7c47f5d9.zip
  .yarn/cache/cookie-parser-npm-1.4.6-a68f84d02a-1e5a63aa82.zip
  package.json
  server/server.ts
  yarn.lock
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-105

#107 Adding more logs to debug session issue
  Jenkinsfile_CNP
  server/server.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-107

#109 DMP-436 pre authentication landing screen
  cypress/e2e/smoke/smoke-spec.cy.js
  src/app/components/login/login.component.html
  src/app/components/login/login.component.spec.ts
  src/app/components/login/login.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-109

#116 Dmp 361 preview
  server/views/azuread-b2c-login.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-116

#121 Dmp 361 ext sign in
  server/views/azuread-b2c-login.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-121

#123 DMP361 : feature : footer fix & positioning
  server/views/azuread-b2c-login.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-123
