Repository hmcts/darts-portal, pull requests merged in 2023-07, with the labels that each got.

#122 DMP-493 Forgotten Password Request Email Code
  server/assets/stylesheets/govuk-forgot-password-email.css
  server/views/azuread-b2c-login.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-122

#128 Replacing the licence logo in the footer with an img tag
  server/assets/images/licence-logo.png
  server/views/azuread-b2c-login.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-128

#139 DMP 494 Forgotten Password Verify Code
  server/assets/javascripts/email-address-disable.js
  server/assets/stylesheets/govuk-custom-styling.css
  server/assets/stylesheets/govuk-forgot-password-email.css
  server/views/azuread-b2c-login.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-139

#141 DMP-590 : fixing tester QA issues
  server/assets/images/govuk-crest-white.png
  server/views/azuread-b2c-login.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-141

#142 DMP-490 Logout
  darts-api-stub/authentication/external.js
  darts-api-stub/views/external-logout.ejs
  server/controllers/api.ts
  server/controllers/authentication.ts
  src/app/components/layout/header/header.component.html
  src/app/components/layout/header/header.component.spec.ts
  src/app/components/layout/header/header.component.ts
  src/app/services/auth/auth.service.spec.ts
  src/app/services/auth/auth.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-142

#145 DMP 494 Forgotten Password Verify Code
  server/assets/javascripts/email-address-disable.js
  server/assets/stylesheets/govuk-custom-styling.css
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-145

#146 DMP 494 Forgotten Password Verify Code
  .yarn/cache/@nx-nx-darwin-arm64-npm-16.5.1-77608b0a77-8.zip
  server/assets/javascripts/email-address-disable.js
  server/assets/stylesheets/govuk-custom-styling.css
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-146

#147 patch : correcting css ID conflict
  server/views/azuread-b2c-login.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-147

#149 Dmp 494 forgotten password verify code
  server/assets/javascripts/email-address-disable.js
  server/views/azuread-b2c-login.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-149

#150 dmp-625 : feat : add display condition to outro text
  server/controllers/auth.ts
  server/views/azuread-b2c-login.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-150

#151 Adding JS in the way Azure accepts it
  server/assets/javascripts/login.js
  server/assets/javascripts/reset-password.js
  server/assets/stylesheets/login.css
  server/assets/stylesheets/reset-password.css
  server/views/azuread-b2c-login.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-151

#152 Removing embedded Javascript
  server/views/azuread-b2c-login.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-152

#153 Removing more embedded Javascript
  .prettierignore
  server/views/azuread-b2c-login.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-153

#158 DMP-493 styling fixes
  server/assets/stylesheets/reset-password.css
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-158

#159 Dmp 493 styling fixes
  server/assets/stylesheets/reset-password.css
  server/views/azuread-b2c-login.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-159

#161 Error message and summary added
  src/app/components/login/login.component.html
  src/app/components/login/login.component.spec.ts
  src/app/components/login/login.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-161

#166 DMP-494-Forgotton-Password-Verify-Code
  server/assets/javascripts/reset-password.js
  server/assets/stylesheets/reset-password.css
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-166

#168 DMP-493-Forgotten-Password-Request-Code
  server/assets/javascripts/reset-password.js
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-168

#170 DMP-585 Password reset flow - code accepted screen
  server/assets/javascripts/reset-password.js
  server/assets/stylesheets/reset-password.css
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-170

#171 DMP-494-Forgotten-Password-Verify-Code
  server/assets/javascripts/reset-password.js
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-171

#172 DMP-585 Password reset flow - code accepted screen fixes
  server/assets/javascripts/reset-password.js
  server/assets/stylesheets/reset-password.css
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-172

#176 DMP-585 Password reset flow - code accepted more change account fixes
  server/assets/javascripts/reset-password.js
  server/assets/stylesheets/reset-password.css
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-176

#181 DMP-594-Create-New-Password
  server/assets/stylesheets/change-password.css
  server/assets/stylesheets/reset-password.css
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-181

#185 Dmp 507 simple case search
  server/assets/javascripts/search.js
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/search/search.component.css
  src/app/components/search/search.component.html
  src/app/components/search/search.component.spec.ts
  src/app/components/search/search.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-185

#186 DMP-585-Code-Accepted
  server/assets/javascripts/reset-password.js
  server/assets/stylesheets/reset-password.css
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-186
