Repository hmcts/darts-portal, pull requests merged in 2023-08, with the labels that each got.

#187 DMP-585-Code-Accepted
  server/assets/javascripts/reset-password.js
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-187

#188 DMP-585-Code-Accepted
  server/assets/javascripts/reset-password.js
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-188

#190 DMP-627 New SecurityToken object for handle-oauth api, new classes an…
  server/controllers/api.ts
  server/controllers/authentication.ts
  server/middleware/is-authenticated.ts
  server/types/classes/securityToken.ts
  server/types/classes/userState.ts
  server/types/session.d.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-190

#198 Dmp 627
  darts-api-stub/authentication/external.js
  server/middleware/is-authenticated.ts
  server/types/classes/userState.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-198

#200 Dmp 507 search cases
  server/assets/javascripts/search.js
  src/app/app.module.ts
  src/app/components/search/search.component.html
  src/app/components/search/search.component.spec.ts
  src/app/components/search/search.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-200

#199 dummy Update README.md
  README.md
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-199

#205 dmp-507 : patch : mouse cursor change on the clear search link
  src/app/components/search/search.component.css
  src/styles.scss
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-205

#195 Dmp 508
  src/app/components/search/search.component.css
  src/app/components/search/search.component.html
  src/app/components/search/search.component.spec.ts
  src/app/components/search/search.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-195

#206 dmp-507 : patch : fix missing tabbed link
  src/app/components/search/search.component.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-206

#207 DMP-720 Handling reset password now it's a separate Azure AD B2C policy
  package.json
  scripts/verify-stg-access.ts
  server/controllers/authentication.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-207

#210 DMP-541 External sign-in errors fixes
  server/assets/javascripts/login.js
  server/views/azuread-b2c-login.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-210

#213 DMP-541 Fixing item level error message styling for external login page
  server/views/azuread-b2c-login.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-213

#214 Trying to fix the wrapXhrOpen call in the external login page
  server/assets/javascripts/login.js
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-214

#218 Dmp 590 qa comments
  server/assets/stylesheets/login.css
  server/views/azuread-b2c-login.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-218

#212 Dmp 517 case search results
  .yarn/cache/@esbuild-darwin-x64-npm-0.18.17-ba2fb6909d-8.zip
  .yarn/cache/@esbuild-darwin-x64-npm-0.18.20-767fe27d1b-8.zip
  .yarn/cache/@nx-nx-darwin-x64-npm-16.5.1-f441b9d7df-8.zip
  darts-api-stub/case/case.js
  darts-api-stub/index.js
  src/app/app.module.ts
  src/app/components/search/results/results.component.css
  src/app/components/search/results/results.component.html
  src/app/components/search/results/results.component.spec.ts
  src/app/components/search/results/results.component.ts
  src/app/components/search/search.component.html
  src/app/components/search/search.component.spec.ts
  src/app/components/search/search.component.ts
  src/app/services/case/case.service.spec.ts
  src/app/services/case/case.service.ts
  src/app/services/datetime/datetime.service.spec.ts
  src/app/services/datetime/datetime.service.ts
  src/app/types/case.d.ts
  src/app/types/hearing.d.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-212

#224 DMP-363 Styling tweaks for external login page
  server/assets/stylesheets/login.css
  server/views/azuread-b2c-login.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-224

#223 DMP-786: Add lazy loading and standalone components
  angular.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/app.routes.spec.ts
  src/app/app.routes.ts
  src/app/components/app.component.spec.ts
  src/app/components/app.component.ts
  src/app/components/audios/audios.component.spec.ts
  src/app/components/audios/audios.component.ts
  src/app/components/home/home.component.spec.ts
  src/app/components/home/home.component.ts
  src/app/components/inbox/inbox.component.spec.ts
  src/app/components/inbox/inbox.component.ts
  src/app/components/layout/content/content.component.spec.ts
  src/app/components/layout/content/content.component.ts
  src/app/components/layout/footer/footer.component.spec.ts
  src/app/components/layout/footer/footer.component.ts
  src/app/components/layout/header/header.component.spec.ts
  src/app/components/layout/header/header.component.ts
  src/app/components/layout/phase-banner/phase-banner.component.spec.ts
  src/app/components/layout/phase-banner/phase-banner.component.ts
  src/app/components/login/login.component.spec.ts
  src/app/components/login/login.component.ts
  src/app/components/search/results/results.component.spec.ts
  src/app/components/search/results/results.component.ts
  src/app/components/search/search.component.spec.ts
  src/app/components/search/search.component.ts
  src/app/components/transcriptions/transcriptions.component.spec.ts
  src/app/components/transcriptions/transcriptions.component.ts
  src/main.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-223

#219 DMP-515-date-pickers
  .pnp.cjs
  .pnp.loader.mjs
  .yarn/cache/@esbuild-darwin-arm64-npm-0.18.17-4da6dfeef9-8.zip
  .yarn/cache/@esbuild-darwin-arm64-npm-0.18.20-00b3504077-8.zip
  .yarn/cache/@scottish-government-pattern-library-npm-0.0.359-76f3c7feaa-7136ea957b.zip
  .yarnrc.yml
  angular.json
  package.json
  src/app/components/search/search.component.html
  src/app/components/search/search.component.ts
  src/assets/datepicker.scss
  src/styles.scss
  src/types.d.ts
  webpack.config.js
  yarn.lock
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-219

#232 DMP-787: Migrate to Jest
  angular.json
  jest.config.ts
  karma.conf.js
  package.json
  setup-jest.ts
  src/app/app.routes.spec.ts
  src/app/auth/auth.guard.spec.ts
  src/app/components/layout/header/header.component.spec.ts
  src/app/components/login/login.component.spec.ts
  src/app/components/search/results/results.component.spec.ts
  src/app/components/search/search.component.spec.ts
  src/app/services/app-config/app-config.service.spec.ts
  src/app/services/app-insights/app-insights.service.spec.ts
  src/app/services/auth/auth.service.spec.ts
  src/app/services/case/case.service.spec.ts
  src/app/services/datetime/datetime.service.spec.ts
  src/app/services/error/error-handler.service.spec.ts
  tsconfig.spec.json
  yarn.lock
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-232

#251 DMP-804: Display reporting restriction to case search results
  src/app/components/search/results/results.component.html
  src/app/components/search/results/results.component.scss
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-251
