Repository hmcts/darts-portal, pull requests merged in 2023-10, with the labels that each got.

#359 DMP-997 breadcrumb for case file
  src/app/components/case/case.component.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-359

#365 DMP-965 sorting for numbers, dates, array on data table
  darts-api-stub/cases/case.js
  src/app/components/case/hearing-results/hearing-results.component.ts
  src/app/components/common/data-table/data-table.component.spec.ts
  src/app/components/common/data-table/data-table.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-365

#353 DMP-963: Save last search
  cypress/e2e/functional/case-search-spec.cy.js
  src/app/components/common/courthouse/courthouse.component.html
  src/app/components/common/courthouse/courthouse.component.spec.ts
  src/app/components/common/courthouse/courthouse.component.ts
  src/app/components/search/results/results.component.html
  src/app/components/search/results/results.component.ts
  src/app/components/search/search-error/search-error.component.html
  src/app/components/search/search-error/search-error.component.scss
  src/app/components/search/search-error/search-error.component.spec.ts
  src/app/components/search/search-error/search-error.component.ts
  src/app/components/search/search.component.html
  src/app/components/search/search.component.spec.ts
  src/app/components/search/search.component.ts
  src/app/services/case/case.service.spec.ts
  src/app/services/case/case.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-353

#373 DMP-1094 Setting audio request userID
  src/app/components/hearing/hearing.component.html
  src/app/components/hearing/order-confirmation/order-confirmation.component.ts
  src/app/components/hearing/request-playback-audio/request-playback-audio.component.spec.ts
  src/app/components/hearing/request-playback-audio/request-playback-audio.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-373

#368 DMP-694-Request-Playback-Audio-Errors
  src/app/components/hearing/hearing.component.html
  src/app/components/hearing/hearing.component.spec.ts
  src/app/components/hearing/hearing.component.ts
  src/app/components/hearing/request-playback-audio/request-playback-audio.component.html
  src/app/components/hearing/request-playback-audio/request-playback-audio.component.scss
  src/app/components/hearing/request-playback-audio/request-playback-audio.component.ts
  src/app/components/hearing/request-playback-audio/time-input/time-input.component.html
  src/app/components/hearing/request-playback-audio/time-input/time-input.component.scss
  src/app/components/hearing/request-playback-audio/time-input/time-input.component.ts
  src/app/components/search/search.component.spec.ts
  src/app/components/search/search.component.ts
  src/app/types/error-summary-entry.interface.ts
  src/app/types/field-errors.interface.ts
  src/app/types/index.ts
  src/app/validators/time-group.validator.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-368

#362 DMP-697: 'Your Audio' screen
  cypress/e2e/functional/your-audio-spec.cy.js
  darts-api-stub/audios/audios.js
  jest.config.ts
  pa11y/pa11y.ts
  package.json
  src/app/app.routes.spec.ts
  src/app/app.routes.ts
  src/app/components/audios/audios.component.html
  src/app/components/audios/audios.component.scss
  src/app/components/audios/audios.component.spec.ts
  src/app/components/audios/audios.component.ts
  src/app/components/case/hearing-results/hearing-results.component.html
  src/app/components/case/hearing-results/hearing-results.component.ts
  src/app/components/common/data-table/data-table.component.html
  src/app/components/common/data-table/data-table.component.scss
  src/app/components/common/data-table/data-table.component.spec.ts
  src/app/components/common/data-table/data-table.component.ts
  src/app/components/common/tabs/tabs.component.html
  src/app/components/common/tabs/tabs.component.scss
  src/app/components/common/tabs/tabs.component.spec.ts
  src/app/components/common/tabs/tabs.component.ts
  src/app/components/hearing/hearing.component.html
  src/app/components/hearing/hearing.component.ts
  src/app/components/hearing/order-confirmation/order-confirmation.component.html
  src/app/components/hearing/order-confirmation/order-confirmation.component.ts
  src/app/components/hearing/request-playback-audio/request-playback-audio.component.spec.ts
  src/app/components/hearing/request-playback-audio/request-playback-audio.component.ts
  src/app/components/inbox/inbox.component.html
  src/app/components/inbox/inbox.component.spec.ts
  src/app/components/inbox/inbox.component.ts
  src/app/components/search/results/results.component.html
  src/app/components/search/results/results.component.spec.ts
  src/app/components/search/results/results.component.ts
  src/app/directives/tab.directive.spec.ts
  src/app/directives/tab.directive.ts
  src/app/directives/table-body-template.directive.spec.ts
  src/app/directives/table-body-template.directive.ts
  src/app/directives/table-row-template.directive.spec.ts
  src/app/directives/table-row-template.directive.ts
  src/app/services/audio/audio.service.spec.ts
  src/app/services/audio/audio.service.ts
  src/app/types/index.ts
  src/app/types/user-audio-request-row.interface.ts
  src/app/types/user-audio-request.interface.ts
  src/styles.scss
  tsconfig.json
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-362

#381 DMP-730: Expired Audio Tab
  cypress/e2e/functional/your-audio-spec.cy.js
  src/app/components/audios/audios.component.html
  src/app/components/audios/audios.component.ts
  src/app/components/case/hearing-results/hearing-results.component.ts
  src/app/components/common/data-table/data-table.component.spec.ts
  src/app/components/common/data-table/data-table.component.ts
  src/app/components/common/tabs/tabs.component.ts
  src/app/components/search/results/results.component.ts
  src/app/directives/tab.directive.spec.ts
  src/app/directives/tab.directive.ts
  src/app/types/data-table-column.interface.ts
  src/app/types/data-table-row.interface.ts
  src/app/types/index.ts
  src/app/types/user-audio-request-row.interface.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-381

#383 Observable User Service
  src/app/app.routes.spec.ts
  src/app/components/hearing/hearing.component.spec.ts
  src/app/services/user/user.service.spec.ts
  src/app/services/user/user.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-383

#377 DMP-696-Request-Audio-Transcribers-Only
  darts-api-stub/authentication/external.js
  src/app/app.routes.spec.ts
  src/app/components/hearing/hearing.component.spec.ts
  src/app/components/hearing/request-playback-audio/request-playback-audio.component.html
  src/app/components/hearing/request-playback-audio/request-playback-audio.component.scss
  src/app/components/hearing/request-playback-audio/request-playback-audio.component.spec.ts
  src/app/components/hearing/request-playback-audio/request-playback-audio.component.ts
  src/app/services/user/user.service.spec.ts
  src/app/services/user/user.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-377

#384 DMP-1204-Date-Fields-Labels
  src/app/components/search/search.component.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-384

#385 DMP-1210-Time-Input-Labels
  src/app/components/hearing/request-playback-audio/time-input/time-input.component.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-385

#386 DMP-966: Update events and audio table
  src/app/components/audios/audios.component.html
  src/app/components/common/audio-player/audio-player.component.html
  src/app/components/common/audio-player/audio-player.component.scss
  src/app/components/common/data-table/data-table.component.html
  src/app/components/common/data-table/data-table.component.scss
  src/app/components/common/data-table/data-table.component.spec.ts
  src/app/components/common/data-table/data-table.component.ts
  src/app/components/hearing/events-and-audio/events-and-audio.component.html
  src/app/components/hearing/events-and-audio/events-and-audio.component.scss
  src/app/components/hearing/events-and-audio/events-and-audio.component.spec.ts
  src/app/components/hearing/events-and-audio/events-and-audio.component.ts
  src/app/components/hearing/hearing.component.spec.ts
  src/app/components/hearing/hearing.component.ts
  src/app/types/hearing-audio-event.interface.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-386

#391 DMP-621-External-To-Internal-Link
  server/views/azuread-b2c-login.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-391

#394 DMP-1242-Removed-Pattern-Error-Message
  src/app/components/hearing/request-playback-audio/request-playback-audio.component.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-394

#393 Upgrading node.js helm chart to v3.0.0
  charts/darts-portal/Chart.yaml
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-393

#396 Map hearing date responses to UTC format
  src/app/components/audios/audios.component.ts
  src/app/components/hearing/order-confirmation/order-confirmation.component.html
  src/app/components/hearing/request-playback-audio/request-playback-audio.component.ts
  src/app/services/audio/audio.service.spec.ts
  src/app/services/audio/audio.service.ts
  src/app/services/case/case.service.spec.ts
  src/app/services/case/case.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-396

#399 DMP-965: Bug fix for date sort on data tables
  darts-api-stub/audios/audios.js
  src/app/components/audios/audios.component.html
  src/app/components/audios/audios.component.scss
  src/app/components/audios/audios.component.ts
  src/app/components/case/hearing-results/hearing-results.component.html
  src/app/components/case/hearing-results/hearing-results.component.scss
  src/app/components/case/hearing-results/hearing-results.component.ts
  src/app/components/common/data-table/data-table.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-399

#402 DMP-781-Search-Results-Loading
  src/app/components/search/search.component.html
  src/app/components/search/search.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-402

#404 Adding disableCleanupOfHelmReleaseOnFailure() to jenkinsfile
  Jenkinsfile_CNP
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-404

#403 DMP-1208 Update pa11y and accessibility fixes
  pa11y/pa11y.ts
  src/app/components/audios/audios.component.ts
  src/app/components/common/data-table/data-table.component.html
  src/app/components/common/reporting-restriction/reporting-restriction.component.html
  src/app/components/hearing/events-and-audio/events-and-audio.component.html
  src/app/components/hearing/events-and-audio/events-and-audio.component.spec.ts
  src/app/components/hearing/events-and-audio/events-and-audio.component.ts
  src/app/components/hearing/request-playback-audio/time-input/time-input.component.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-403

#405 Setting app-insights cloud role name
  src/app/services/app-insights/app-insights.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-405

#411 DMP-434 kv secret reference for express middleware
  charts/darts-portal/Chart.yaml
  charts/darts-portal/values.yaml
  config/default.json
  server/middleware/session.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-411

#414 DMP-681 Password reset errors on b2c pages
  server/assets/javascripts/errors.js
  server/assets/javascripts/login.js
  server/assets/javascripts/reset-password.js
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-414

#406 DMP-836 & DMP-837: Delete audio requests
  cypress/e2e/functional/your-audio-spec.cy.js
  darts-api-stub/audios/audios.js
  src/app/components/app.component.spec.ts
  src/app/components/app.component.ts
  src/app/components/audios/audios.component.html
  src/app/components/audios/audios.component.scss
  src/app/components/audios/audios.component.spec.ts
  src/app/components/audios/audios.component.ts
  src/app/components/case/hearing-results/hearing-results.component.html
  src/app/components/common/tabs/tabs.component.html
  src/app/components/common/tabs/tabs.component.spec.ts
  src/app/components/common/tabs/tabs.component.ts
  src/app/components/layout/header/header.component.spec.ts
  src/app/directives/tab.directive.ts
  src/app/services/audio/audio.service.spec.ts
  src/app/services/audio/audio.service.ts
  src/app/types/user-audio-request-row.interface.ts
  src/app/types/user-audio-request.interface.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-406

#420 PR/staging environment pipeline deployment fix
  charts/darts-portal/values.dev.template.yaml
  charts/darts-portal/values.stg.template.yaml
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-420

#422 DMP-681 Azure B2C change password verification token error formatting
  server/assets/javascripts/errors.js
  server/assets/javascripts/login.js
  server/assets/javascripts/reset-password.js
  server/assets/stylesheets/login.css
  server/assets/stylesheets/reset-password.css
  server/views/azuread-b2c-login.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-422

#424 DMP-681 B2C Styling for verification code
  server/assets/javascripts/errors.js
  server/assets/javascripts/login.js
  server/assets/javascripts/reset-password.js
  server/assets/stylesheets/reset-password.css
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-424

#426 DMP-550 reset password new password validation
  server/assets/javascripts/change-password.js
  server/assets/javascripts/errors.js
  server/assets/stylesheets/change-password.css
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-426

#425 DMP-681 b2c errors reset password
  server/assets/javascripts/errors.js
  server/assets/javascripts/reset-password.js
  server/assets/stylesheets/reset-password.css
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-425

#419 fix fieldId console error
  src/app/components/hearing/hearing.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-419

#421 DMP-739: View / Download Audio
  cypress/e2e/functional/your-audio-spec.cy.js
  darts-api-stub/audios/audios.js
  darts-api-stub/audios/preview/preview.mp3.zip
  src/app/components/audios/audio-view/audio-view.component.html
  src/app/components/audios/audio-view/audio-view.component.scss
  src/app/components/audios/audio-view/audio-view.component.spec.ts
  src/app/components/audios/audio-view/audio-view.component.ts
  src/app/components/audios/audios.component.html
  src/app/components/audios/audios.component.spec.ts
  src/app/components/audios/audios.component.ts
  src/app/components/layout/header/header.component.spec.ts
  src/app/components/layout/header/header.component.ts
  src/app/services/audio-request/audio-request.service.spec.ts
  src/app/services/audio-request/audio-request.service.ts
Labels: ns:darts-modernisation, prd:darts, enable_keep_helm, rel:darts-portal-pr-421

#423 DMP-838: Delete audio from download screen
  .gitignore
  cypress/e2e/functional/your-audio-spec.cy.js
  src/app/components/audios/audio-delete/audio-delete.component.html
  src/app/components/audios/audio-delete/audio-delete.component.scss
  src/app/components/audios/audio-delete/audio-delete.component.spec.ts
  src/app/components/audios/audio-delete/audio-delete.component.ts
  src/app/components/audios/audio-view/audio-view.component.html
  src/app/components/audios/audio-view/audio-view.component.scss
  src/app/components/audios/audio-view/audio-view.component.ts
  src/app/components/audios/audios.component.html
  src/app/components/audios/audios.component.ts
  src/app/components/case/case.component.html
  src/app/components/case/case.component.scss
  src/app/components/case/case.component.ts
  src/app/components/common/breadcrumb/breadcrumb.component.html
  src/app/components/common/breadcrumb/breadcrumb.component.scss
  src/app/components/common/breadcrumb/breadcrumb.component.spec.ts
  src/app/components/common/breadcrumb/breadcrumb.component.ts
  src/app/components/hearing/hearing.component.html
  src/app/components/hearing/hearing.component.scss
  src/app/components/hearing/hearing.component.ts
  src/app/directives/breadcrumb.directive.spec.ts
  src/app/directives/breadcrumb.directive.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-423

#436 DMP-681 B2C Verification code error formatting reset pwd
  server/assets/javascripts/reset-password.js
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-436

#435 DMP-550 B2C change password validation error summary
  server/assets/stylesheets/change-password.css
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-435

#434 pa11y updates to show only new issues, flag to ignore known
  pa11y/pa11y.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-434

#442 DMP-681 Reset & Change pwd css styling for errors
  server/assets/javascripts/reset-password.js
  server/assets/stylesheets/change-password.css
  server/assets/stylesheets/reset-password.css
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-442

#437 Adding some logs to API proxy
  server/controllers/api.ts
Labels: ns:darts-modernisation, prd:darts, enable_keep_helm, rel:darts-portal-pr-437

#447 DMP-1245 b2c change password email address validation
  server/assets/javascripts/errors.js
  server/assets/javascripts/reset-password.js
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-447

#446 DMP:1277: Fix date bug for Safari and Firefox
  src/app/components/hearing/request-playback-audio/request-playback-audio.component.ts
  src/app/services/audio-request/audio-request.service.spec.ts
  src/app/services/audio-request/audio-request.service.ts
  src/app/services/case/case.service.spec.ts
  src/app/services/case/case.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-446

#453 Adding bits for testing audio streaming issue
  server/controllers/api.ts
  server/routes.ts
  src/app/components/hearing/events-and-audio/events-and-audio.component.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-453

#454 Amending logging for test audio API request
  server/routes.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-454

#448 DMP-1245 B2C Email error formatting
  server/assets/javascripts/reset-password.js
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-448

#445 DMP-1114: Clear failed audio request
  cypress/e2e/functional/your-audio-spec.cy.js
  darts-api-stub/audios/audios.js
  src/app/components/app.component.spec.ts
  src/app/components/app.component.ts
  src/app/components/audios/audio-delete/audio-delete.component.spec.ts
  src/app/components/audios/audio-delete/audio-delete.component.ts
  src/app/components/audios/audios.component.html
  src/app/components/audios/audios.component.ts
  src/app/components/hearing/hearing.component.html
  src/app/components/hearing/hearing.component.scss
  src/app/components/hearing/hearing.component.spec.ts
  src/app/components/hearing/hearing.component.ts
  src/app/components/hearing/order-confirmation/order-confirmation.component.spec.ts
  src/app/components/hearing/order-confirmation/order-confirmation.component.ts
  src/app/services/header/header.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-445

#412 DMP-769-Case-File-All-Transcripts
  cypress/e2e/functional/case-file-spec.cy.js
  darts-api-stub/cases/case.js
  src/app/components/audios/audio-delete/audio-delete.component.html
  src/app/components/audios/audios.component.html
  src/app/components/case/case.component.html
  src/app/components/case/case.component.spec.ts
  src/app/components/case/case.component.ts
  src/app/components/case/hearing-results/hearing-results.component.html
  src/app/components/case/hearing-results/hearing-results.component.ts
  src/app/components/common/data-table/data-table.component.html
  src/app/components/common/data-table/data-table.component.spec.ts
  src/app/components/common/data-table/data-table.component.ts
  src/app/components/common/tabs/tabs.component.html
  src/app/components/common/tabs/tabs.component.scss
  src/app/components/hearing/events-and-audio/events-and-audio.component.html
  src/app/components/search/results/results.component.ts
  src/app/directives/tab.directive.ts
  src/app/directives/table-row-template.directive.ts
  src/app/services/case/case.service.spec.ts
  src/app/services/case/case.service.ts
  src/app/types/data-table-column.interface.ts
  src/app/types/data-table-row.interface.ts
  src/app/types/index.ts
  src/app/types/transcript.interface.ts
  src/app/types/transcripts-row.interface.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-412

#459 DMP-769: Case file All transcripts
  cypress/e2e/functional/case-file-spec.cy.js
  darts-api-stub/cases/case.js
  src/app/components/case/case.component.spec.ts
  src/app/components/case/case.component.ts
  src/app/components/case/hearing-results/hearing-results.component.html
  src/app/components/case/hearing-results/hearing-results.component.ts
  src/app/services/case/case.service.spec.ts
  src/app/services/case/case.service.ts
  src/app/types/transcript.interface.ts
  src/app/types/transcripts-row.interface.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-459

#464 Fix breadcrumb markup
  src/app/components/audios/audio-view/audio-view.component.html
  src/app/components/case/case.component.html
  src/app/components/hearing/hearing.component.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-464

#461 Login-Redirect-Fix
  cypress/e2e/functional/auth-spec.cy.js
  cypress/e2e/functional/commands.js
  src/app/app.routes.spec.ts
  src/app/app.routes.ts
  src/app/auth/auth.guard.ts
  src/app/components/home/home.component.html
  src/app/components/home/home.component.scss
  src/app/components/home/home.component.spec.ts
  src/app/components/home/home.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-461

#467 Removing some unnecessary commands from the Jenkinsfile
  Jenkinsfile_CNP
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-467

#468 Adding option to allow auth bootstrap
  config/custom-environment-variables.json
  config/default.json
  server/controllers/authentication.ts
  server/utils/base64.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-468

#466 DMP-1330: Unread count endpoint
  cypress/e2e/functional/your-audio-spec.cy.js
  darts-api-stub/audios/audios.js
  src/app/app.routes.spec.ts
  src/app/app.routes.ts
  src/app/components/hearing/hearing.component.spec.ts
  src/app/components/hearing/request-playback-audio/request-playback-audio.component.spec.ts
  src/app/components/layout/header/header.component.html
  src/app/components/layout/header/header.component.spec.ts
  src/app/components/layout/header/header.component.ts
  src/app/services/audio-request/audio-request.service.spec.ts
  src/app/services/audio-request/audio-request.service.ts
  src/app/services/user/user.service.spec.ts
  src/app/services/user/user.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-466

#477 Auth bootstrap - Do not redirect
  server/controllers/authentication.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-477

#478 Allow secure cookies to be disabled
  config/custom-environment-variables.json
  config/default.json
  config/development.json
  server/middleware/session.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-478

#471 DMP-862-Hearings-Transcript-Tab
  cypress/e2e/functional/hearing-transcripts-spec.cy.js
  darts-api-stub/hearings/hearings.js
  src/app/components/case/case.component.ts
  src/app/components/hearing/events-and-audio/events-and-audio.component.ts
  src/app/components/hearing/hearing.component.html
  src/app/components/hearing/hearing.component.scss
  src/app/components/hearing/hearing.component.spec.ts
  src/app/components/hearing/hearing.component.ts
  src/app/services/case/case.service.spec.ts
  src/app/services/case/case.service.ts
  src/app/services/mapping/mapping.service.spec.ts
  src/app/services/mapping/mapping.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-471

#469 DMP-1323 Generic internal server error page, unit tests, functional tests
  cypress/e2e/functional/case-search-spec.cy.js
  cypress/e2e/functional/error-spec.cy.js
  darts-api-stub/cases/case.js
  pa11y/pa11y.ts
  src/app/app.routes.ts
  src/app/components/error/internal-server/internal-error.component.html
  src/app/components/error/internal-server/internal-error.component.scss
  src/app/components/error/internal-server/internal-error.component.spec.ts
  src/app/components/error/internal-server/internal-error.component.ts
  src/app/components/hearing/events-and-audio/events-and-audio.component.ts
  src/app/components/search/search-error/search-error.component.html
  src/app/components/search/search-error/search-error.component.spec.ts
  src/app/components/search/search-error/search-error.component.ts
  src/app/components/search/search.component.spec.ts
  src/app/components/search/search.component.ts
  src/app/interceptors/error/error.interceptor.spec.ts
  src/app/interceptors/error/error.interceptor.ts
  src/app/services/audio-request/audio-request.service.spec.ts
  src/app/services/error/error-message.service.spec.ts
  src/app/services/error/error-message.service.ts
  src/app/types/error-message.interface.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-469
