Repository hmcts/darts-portal, pull requests merged in 2024-01, with the labels that each got.

#688 DMP-1489
  src/app/components/common/data-table/data-table.component.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-688

#687 DMP-1369 Retention link
  cypress/e2e/functional/case-file-spec.cy.js
  darts-api-stub/cases/case.js
  src/app/components/case/case-file/case-file.component.html
  src/app/components/case/case-file/case-file.component.scss
  src/app/components/case/case-file/case-file.component.spec.ts
  src/app/components/case/case-file/case-file.component.ts
  src/app/components/case/case.component.spec.ts
  src/app/services/user/user.service.ts
  src/app/types/user-state.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-687

#690 DMP-1488 - Error 409 - duplicate audio request
  cypress/e2e/functional/request-audio-spec.cy.js
  darts-api-stub/audios/audio-requests.js
  src/app/components/hearing/hearing.component.html
  src/app/components/hearing/hearing.component.spec.ts
  src/app/services/error/error-message.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-690

#689 DMP-1835-Change-Media-Request-Endpoint
  darts-api-stub/audios/audio-requests.js
  src/app/components/audios/audio-view/audio-view.component.spec.ts
  src/app/components/audios/audio-view/audio-view.component.ts
  src/app/components/audios/audios.component.spec.ts
  src/app/components/audios/audios.component.ts
  src/app/services/audio-request/audio-request.service.spec.ts
  src/app/services/audio-request/audio-request.service.ts
  src/app/types/audio-request-row.interface.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-689

#684 DMP-1606: Add support for multiple reporting restrictions on case file view
  cypress/e2e/functional/case-file-spec.cy.js
  cypress/e2e/functional/case-search-spec.cy.js
  darts-api-stub/cases/case.js
  src/app/components/case/case-file/case-file.component.html
  src/app/components/common/govuk-details/govuk-details.component.html
  src/app/components/common/govuk-details/govuk-details.component.scss
  src/app/components/common/govuk-details/govuk-details.component.spec.ts
  src/app/components/common/govuk-details/govuk-details.component.ts
  src/app/components/common/reporting-restriction/reporting-restriction.component.html
  src/app/components/common/reporting-restriction/reporting-restriction.component.scss
  src/app/components/common/reporting-restriction/reporting-restriction.component.ts
  src/app/components/search/results/results.component.html
  src/app/types/case.interface.ts
  src/app/types/index.ts
  src/app/types/reporting-restriction.interface.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-684

#695 DMP-1764-Change-Media-Request-Patch-Endpoint
  darts-api-stub/audios/audio-requests.js
  src/app/components/audios/audio-view/audio-view.component.spec.ts
  src/app/components/audios/audio-view/audio-view.component.ts
  src/app/services/audio-request/audio-request.service.spec.ts
  src/app/services/audio-request/audio-request.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-695

#699 DMP-1925 Loading bug
  src/app/components/search/search.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-699

#691 DMP-1406 Case Retention
  cypress/e2e/functional/case-file-spec.cy.js
  cypress/e2e/functional/case-retention-spec.cy.js
  darts-api-stub/cases/case.js
  darts-api-stub/index.js
  darts-api-stub/retentions/retention.js
  src/app/app.routes.ts
  src/app/components/case/case-file/case-file.component.html
  src/app/components/case/case-file/case-file.component.spec.ts
  src/app/components/case/case-file/case-file.component.ts
  src/app/components/case/case-retention-date/case-retention-date.component.html
  src/app/components/case/case-retention-date/case-retention-date.component.scss
  src/app/components/case/case-retention-date/case-retention-date.component.spec.ts
  src/app/components/case/case-retention-date/case-retention-date.component.ts
  src/app/components/common/details-table/details-table.component.html
  src/app/components/common/notification-banner/notification-banner.component.html
  src/app/components/common/notification-banner/notification-banner.component.scss
  src/app/components/common/notification-banner/notification-banner.component.spec.ts
  src/app/components/common/notification-banner/notification-banner.component.ts
  src/app/components/hearing/request-transcript/request-transcript-confirmation/request-transcript-confirmation.component.html
  src/app/components/transcriptions/view-transcript/view-transcript.component.html
  src/app/services/case/case.service.spec.ts
  src/app/services/case/case.service.ts
  src/app/types/case-retention-history.interface.ts
  src/app/types/case.interface.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-691

#694 DMP-1798: Add multiple reporting restrictions to hearing screen
  cypress/e2e/functional/case-file-spec.cy.js
  cypress/e2e/functional/hearing-screen-spec.cy.js
  cypress/e2e/functional/hearing-transcripts-spec.cy.js
  darts-api-stub/cases/case.js
  src/app/components/case/case-file/case-file.component.html
  src/app/components/common/reporting-restriction/reporting-restriction.component.html
  src/app/components/common/reporting-restriction/reporting-restriction.component.ts
  src/app/components/hearing/hearing.component.html
  src/app/components/hearing/hearing.component.spec.ts
  src/app/components/hearing/hearing.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-694

#702 Update axios version to 1.6.5
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-702

#700 DMP-2013-Separate-Delete-Endpoints
  darts-api-stub/audios/audio-requests.js
  src/app/components/audios/audios.component.spec.ts
  src/app/components/audios/audios.component.ts
  src/app/services/audio-request/audio-request.service.spec.ts
  src/app/services/audio-request/audio-request.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-700

#704 DMP-2018
  darts-api-stub/audios/audio-requests.js
  src/app/components/audios/audio-view/audio-view.component.spec.ts
  src/app/components/audios/audio-view/audio-view.component.ts
  src/app/components/audios/audios.component.spec.ts
  src/app/components/audios/audios.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-704

#701 DMP-1799: Multiple reporting restrictions
  darts-api-stub/transcriptions/transcriptions.js
  src/app/components/audios/audio-view/audio-view.component.html
  src/app/components/common/reporting-restriction/reporting-restriction.component.html
  src/app/components/hearing/request-transcript/request-transcript.component.html
  src/app/components/transcriptions/approve-transcript/approve-transcript.component.html
  src/app/components/transcriptions/approve-transcript/approve-transcript.component.spec.ts
  src/app/components/transcriptions/approve-transcript/approve-transcript.component.ts
  src/app/components/transcriptions/assign-transcript/assign-transcript.component.html
  src/app/components/transcriptions/assign-transcript/assign-transcript.component.ts
  src/app/components/transcriptions/view-transcript/approved-transcript/approved-transcript.component.html
  src/app/components/transcriptions/view-transcript/rejected-transcript/rejected-transcript.component.html
  src/app/components/transcriptions/view-transcript/view-transcript.component.html
  src/app/components/your-work/upload-transcript/upload-transcript.component.html
  src/app/components/your-work/upload-transcript/upload-transcript.component.spec.ts
  src/app/components/your-work/upload-transcript/upload-transcript.component.ts
  src/app/types/transcription-details.interface.ts
  src/styles.scss
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-701

#712 DMP-2018: Fix refresh on delete bug in AudiosComponent
  src/app/components/audios/audios.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-712

#709 DMP-1413 - Change retention date screen
  cypress/e2e/functional/case-retention-spec.cy.js
  src/app/components/case/case-retention-change/case-retention-change.component.html
  src/app/components/case/case-retention-change/case-retention-change.component.scss
  src/app/components/case/case-retention-change/case-retention-change.component.spec.ts
  src/app/components/case/case-retention-change/case-retention-change.component.ts
  src/app/components/case/case-retention-date/case-retention-date.component.html
  src/app/components/case/case-retention-date/case-retention-date.component.spec.ts
  src/app/components/case/case-retention-date/case-retention-date.component.ts
  src/app/types/case-retention-page-state.type.ts
  src/styles.scss
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-709

#715 DMP-1875-ITHC-Test
  Jenkinsfile_CNP
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-715

#714 DMP-1836-Update-Download-And-Playback-Logic
  darts-api-stub/audios/audio-requests.js
  src/app/components/audios/audio-view/audio-view.component.spec.ts
  src/app/components/audios/audio-view/audio-view.component.ts
  src/app/services/audio-request/audio-request.service.spec.ts
  src/app/services/audio-request/audio-request.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-714

#725 DMP-1450 - Retention errors
  cypress/e2e/functional/case-retention-spec.cy.js
  src/app/components/case/case-retention-change/case-retention-change.component.html
  src/app/components/case/case-retention-change/case-retention-change.component.spec.ts
  src/app/components/case/case-retention-change/case-retention-change.component.ts
  src/app/components/case/case-retention-date/case-retention-date.component.html
  src/app/components/case/case-retention-date/case-retention-date.component.spec.ts
  src/app/components/case/case-retention-date/case-retention-date.component.ts
  src/app/validators/before-date.validator.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-725

#728 DMP-1810
  src/app/components/common/data-table/data-table.component.html
  src/app/components/your-work/your-work.component.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-728

#713 DMP-1821 Upgrade to govuk-frontend V5
  angular.json
  darts-api-stub/views/login.ejs
  package.json
  server/assets/javascripts/govuk-frontend-4.6.0.min.js
  server/assets/javascripts/govuk-frontend-5.0.0.min.js
  server/assets/stylesheets/govuk-frontend-4.6.0.min.css
  server/assets/stylesheets/govuk-frontend-5.0.0.min.css
  server/views/azuread-b2c-login.html
  src/index.html
  src/styles.scss
  yarn.lock
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-713

#733 DMP-2080 Reporting restriction bug
  darts-api-stub/transcriptions/transcriptions.js
  src/app/components/transcriptions/approve-transcript/approve-transcript.component.spec.ts
  src/app/components/transcriptions/approve-transcript/approve-transcript.component.ts
  src/app/components/transcriptions/assign-transcript/assign-transcript.component.spec.ts
  src/app/components/transcriptions/assign-transcript/assign-transcript.component.ts
  src/app/components/transcriptions/view-transcript/approved-transcript/approved-transcript.component.html
  src/app/components/transcriptions/view-transcript/approved-transcript/approved-transcript.component.spec.ts
  src/app/components/transcriptions/view-transcript/rejected-transcript/rejected-transcript.component.html
  src/app/components/transcriptions/view-transcript/rejected-transcript/rejected-transcript.component.spec.ts
  src/app/components/transcriptions/view-transcript/view-transcript.component.html
  src/app/components/your-work/upload-transcript/upload-transcript.component.spec.ts
  src/app/components/your-work/upload-transcript/upload-transcript.component.ts
  src/app/types/transcription-details.interface.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-733

#738 DMP-2012: Bugfix - transformed media filename
  darts-api-stub/audios/audio-requests.js
  src/app/components/audios/audio-view/audio-view.component.html
  src/app/components/audios/audio-view/audio-view.component.spec.ts
  src/app/components/audios/audio-view/audio-view.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-738

#739 DMP-2036-Textarea-Component
  src/app/components/case/case-retention-change/case-retention-change.component.html
  src/app/components/case/case-retention-change/case-retention-change.component.ts
  src/app/components/common/govuk-textarea/govuk-textarea.component.html
  src/app/components/common/govuk-textarea/govuk-textarea.component.scss
  src/app/components/common/govuk-textarea/govuk-textarea.component.spec.ts
  src/app/components/common/govuk-textarea/govuk-textarea.component.ts
  src/app/components/hearing/request-transcript/request-transcript-confirmation/request-transcript-confirmation.component.html
  src/app/components/hearing/request-transcript/request-transcript-confirmation/request-transcript-confirmation.component.spec.ts
  src/app/components/hearing/request-transcript/request-transcript-confirmation/request-transcript-confirmation.component.ts
  src/app/components/transcriptions/approve-transcript/approve-transcript-buttons/approve-transcript-buttons.component.html
  src/app/components/transcriptions/approve-transcript/approve-transcript-buttons/approve-transcript-buttons.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-739

#741 DMP-2067 Generic filter component
  angular.json
  darts-api-stub/views/login.ejs
  server/app-config.ts
  server/routes.ts
  src/app/app.routes.ts
  src/app/components/common/filters/filter.interface.ts
  src/app/components/common/filters/filters.component.html
  src/app/components/common/filters/filters.component.scss
  src/app/components/common/filters/filters.component.spec.ts
  src/app/components/common/filters/filters.component.ts
  src/app/components/dev/dev.component.html
  src/app/components/dev/dev.component.scss
  src/app/components/dev/dev.component.spec.ts
  src/app/components/dev/dev.component.ts
  src/app/services/app-config/app-config.service.spec.ts
  src/app/services/app-config/app-config.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-741

#734 DMP-1437 - Check your retention date change screen
  cypress/e2e/functional/case-file-spec.cy.js
  cypress/e2e/functional/case-retention-spec.cy.js
  darts-api-stub/cases/case.js
  src/app/components/case/case-retention-date/case-retention-change/case-retention-change.component.html
  src/app/components/case/case-retention-date/case-retention-change/case-retention-change.component.scss
  src/app/components/case/case-retention-date/case-retention-change/case-retention-change.component.spec.ts
  src/app/components/case/case-retention-date/case-retention-change/case-retention-change.component.ts
  src/app/components/case/case-retention-date/case-retention-confirm/case-retention-confirm.component.html
  src/app/components/case/case-retention-date/case-retention-confirm/case-retention-confirm.component.scss
  src/app/components/case/case-retention-date/case-retention-confirm/case-retention-confirm.component.spec.ts
  src/app/components/case/case-retention-date/case-retention-confirm/case-retention-confirm.component.ts
  src/app/components/case/case-retention-date/case-retention-date.component.html
  src/app/components/case/case-retention-date/case-retention-date.component.spec.ts
  src/app/components/case/case-retention-date/case-retention-date.component.ts
  src/app/types/case-retention-page-state.type.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-734

#743 DMP-1439 - Confirmation of retention date change screen
  cypress/e2e/functional/case-retention-spec.cy.js
  darts-api-stub/retentions/retention.js
  src/app/components/case/case-retention-date/case-retention-change/case-retention-change.component.ts
  src/app/components/case/case-retention-date/case-retention-confirm/case-retention-confirm.component.html
  src/app/components/case/case-retention-date/case-retention-confirm/case-retention-confirm.component.spec.ts
  src/app/components/case/case-retention-date/case-retention-confirm/case-retention-confirm.component.ts
  src/app/components/case/case-retention-date/case-retention-date.component.html
  src/app/components/case/case-retention-date/case-retention-date.component.spec.ts
  src/app/components/case/case-retention-date/case-retention-date.component.ts
  src/app/components/common/success-banner/success-banner.component.html
  src/app/components/common/success-banner/success-banner.component.scss
  src/app/components/common/success-banner/success-banner.component.spec.ts
  src/app/components/common/success-banner/success-banner.component.ts
  src/app/services/case/case.service.spec.ts
  src/app/services/case/case.service.ts
  src/app/types/case-retention-change.interface.ts
  src/app/types/case-retention-page-state.type.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-743

#754 Minor dev/components tweaks
  src/app/app.routes.ts
  src/app/components/dev/dev.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-754

#751 DMP-1803-Case-Search-Endpoint-Update
  darts-api-stub/cases/case.js
  src/app/services/case/case.service.spec.ts
  src/app/services/case/case.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-751

#757 DMP-1450 - 2 - Retention errors
  darts-api-stub/retentions/retention.js
  src/app/components/case/case-retention-date/case-retention-change/case-retention-change.component.ts
  src/app/components/case/case-retention-date/case-retention-confirm/case-retention-confirm.component.spec.ts
  src/app/components/case/case-retention-date/case-retention-confirm/case-retention-confirm.component.ts
  src/app/components/case/case-retention-date/case-retention-date.component.spec.ts
  src/app/components/case/case-retention-date/case-retention-date.component.ts
  src/app/services/case/case.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-757

#753 DMP-2034 View Transcript Refactor
  src/app/components/transcriptions/view-transcript/case-hearing-transcript/case-hearing-transcript.component.html
  src/app/components/transcriptions/view-transcript/case-hearing-transcript/case-hearing-transcript.component.scss
  src/app/components/transcriptions/view-transcript/case-hearing-transcript/case-hearing-transcript.component.spec.ts
  src/app/components/transcriptions/view-transcript/case-hearing-transcript/case-hearing-transcript.component.ts
  src/app/components/transcriptions/view-transcript/view-transcript.component.html
  src/app/components/transcriptions/view-transcript/view-transcript.component.spec.ts
  src/app/components/transcriptions/view-transcript/view-transcript.component.ts
  src/app/services/transcription/transcription.service.spec.ts
  src/app/services/transcription/transcription.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-753

#767 DMP-1886
  src/app/components/common/govuk-heading/govuk-heading.component.html
  src/app/components/error/conflict/conflict.component.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-767

#768 DMP-2165
  src/app/components/audios/audios.component.ts
  src/app/constants/transcription-columns.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-768

#766 DMP-2125 Audio request status
  darts-api-stub/audios/audio-requests.js
  src/app/components/audios/audios.component.html
  src/app/components/audios/audios.component.spec.ts
  src/app/components/audios/audios.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-766

#772 DMP-2051 Ignore Audio count API errors
  src/app/services/error/error-message.service.spec.ts
  src/app/services/error/error-message.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-772

#779 DMP-2123/2124: Singular & plural transcript delete screen text
  src/app/components/transcriptions/transcriptions.component.html
  src/app/components/transcriptions/transcriptions.component.spec.ts
  src/app/components/transcriptions/transcriptions.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-779

#780 DMP-1924: Data table bugfix - maintain sorting and paging state on data refresh
  src/app/components/common/data-table/data-table.component.html
  src/app/components/common/data-table/data-table.component.spec.ts
  src/app/components/common/data-table/data-table.component.ts
  src/app/components/search/results/results.component.html
  src/app/services/transcription/transcription.service.spec.ts
  src/app/services/transcription/transcription.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-780

#778 DMP-1926 - UI Bug: Reject transcript validation unexpected behaviour
  cypress/e2e/functional/your-transcripts-spec.cy.js
  src/app/components/transcriptions/approve-transcript/approve-transcript-buttons/approve-transcript-buttons.component.html
  src/app/components/transcriptions/approve-transcript/approve-transcript-buttons/approve-transcript-buttons.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-778

#777 DevComponents: Filter - isChecked added for search changes
  src/app/components/common/filters/filters.component.html
  src/app/components/common/filters/filters.component.spec.ts
  src/app/components/common/filters/filters.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-777

#786 DMP-2085: Add spacing to order request summary and confirmation
  src/app/components/hearing/hearing.component.html
  src/app/components/hearing/hearing.component.scss
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-786

#771 DMP- 2035 - Move datepicker into component and amend usages
  src/app/components/case/case-retention-date/case-retention-change/case-retention-change.component.html
  src/app/components/case/case-retention-date/case-retention-change/case-retention-change.component.scss
  src/app/components/case/case-retention-date/case-retention-change/case-retention-change.component.ts
  src/app/components/common/datepicker/datepicker.component.html
  src/app/components/common/datepicker/datepicker.component.scss
  src/app/components/common/datepicker/datepicker.component.spec.ts
  src/app/components/common/datepicker/datepicker.component.ts
  src/app/components/search/search.component.html
  src/app/components/search/search.component.spec.ts
  src/app/components/search/search.component.ts
  src/styles.scss
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-771

#782 DMP-2048
  server/middleware/is-authenticated.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-782

#787 DP-2188 Data table with no pagination fix
  src/app/components/common/data-table/data-table.component.spec.ts
  src/app/components/common/data-table/data-table.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-787
