Repository hmcts/darts-portal, pull requests merged in 2025-01, with the labels that each got.

#1747 Fixed time based tests
  src/app/admin/components/retention-policies/retention-policy-form/retention-policy-form.component.spec.ts
  src/app/admin/services/retention-policies/retention-policies.service.spec.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-1747

#1736 DMP-4263 New associated hearings table for audio file
  cypress/e2e/functional/admin-portal/audio-file-details-spec.cy.js
  darts-api-stub/admin/medias/medias.js
  src/app/admin/components/audio-file/associated-cases-table/associated-cases-table.component.html
  src/app/admin/components/audio-file/associated-cases-table/associated-cases-table.component.ts
  src/app/admin/components/audio-file/associated-hearings-table/associated-hearings-table.component.html
  src/app/admin/components/audio-file/associated-hearings-table/associated-hearings-table.component.scss
  src/app/admin/components/audio-file/associated-hearings-table/associated-hearings-table.component.spec.ts
  src/app/admin/components/audio-file/associated-hearings-table/associated-hearings-table.component.ts
  src/app/admin/components/audio-file/audio-file.component.html
  src/app/admin/components/audio-file/audio-file.component.spec.ts
  src/app/admin/components/audio-file/audio-file.component.ts
  src/app/admin/components/audio-file/basic-audio-file-details/basic-audio-file-details.component.html
  src/app/admin/components/audio-file/basic-audio-file-details/basic-audio-file-details.component.spec.ts
  src/app/admin/components/audio-file/basic-audio-file-details/basic-audio-file-details.component.ts
  src/app/admin/models/transformed-media/associated-case.ts
  src/app/admin/models/transformed-media/associated-hearing.ts
  src/app/admin/models/transformed-media/audio-file-data.interface.ts
  src/app/admin/models/transformed-media/audio-file.ts
  src/app/admin/services/transformed-media/transformed-media.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-1736

#1750 DMP-4532 Change default sorting for first click to asc
  jest.config.ts
  src/app/core/components/common/data-table/data-table.component.spec.ts
  src/app/core/components/common/data-table/data-table.component.ts
  src/app/core/constants/datetime-keys.ts
Labels: ns:darts-modernisation, prd:darts, enable_keep_helm, rel:darts-portal-pr-1750

#1743 DMP-4506 sort courthouse dropdown by autocomplete
  src/app/admin/services/courthouses/courthouses.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-1743

#1737 DMP-4197 Your audio tab active tab service change
  cypress/e2e/functional/your-audio-spec.cy.js
  src/app/portal/components/audios/audios.component.html
  src/app/portal/components/audios/audios.component.spec.ts
  src/app/portal/components/audios/audios.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-1737

#1742 DMP-4102 Portal - Your transcripts word change
  cypress/e2e/functional/your-transcripts-spec.cy.js
  src/app/portal/components/transcriptions/transcriptions.component.html
  src/app/portal/components/transcriptions/transcriptions.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-1742

#1756 DMP-4102 Text update
  src/app/portal/components/transcriptions/transcriptions.component.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-1756

#1755 DMP-4545 Text update for portal links
  src/app/core/components/layout/header/header.component.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-1755

#1744 DMP-4369 Validation updates across admin forms with cy tests
  cypress/e2e/constants/validation-constants.js
  cypress/e2e/functional/admin-portal/courthouse-record-spec.cy.js
  cypress/e2e/functional/admin-portal/search-spec.cy.js
  cypress/e2e/functional/admin-portal/transcript-requests-spec.cy.js
  cypress/e2e/functional/admin-portal/transformed-media-spec.cy.js
  src/app/admin/components/courthouses/create-courthouse/create-update-courthouse-form/create-update-courthouse-form.component.spec.ts
  src/app/admin/components/courthouses/create-courthouse/create-update-courthouse-form/create-update-courthouse-form.component.ts
  src/app/admin/components/search/search-form/search-form.component.html
  src/app/admin/components/search/search-form/search-form.component.ts
  src/app/admin/components/transcripts/search-transcripts-form/search-transcripts-form.component.html
  src/app/admin/components/transcripts/search-transcripts-form/search-transcripts-form.component.ts
  src/app/admin/components/transformed-media/search-transformed-media-form/search-transformed-media-form.component.html
  src/app/admin/components/transformed-media/search-transformed-media-form/search-transformed-media-form.component.ts
  src/app/admin/constants/admin-search-form-error-messages.ts
  src/app/admin/constants/transcript-search-form-error-messages.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-1744

#1757 DMP-4506 Courthouse fields updated across admin, portal
  src/app/admin/components/transcripts/search-transcripts-form/search-transcripts-form.component.ts
  src/app/admin/components/transcripts/transcripts.component.spec.ts
  src/app/admin/components/transcripts/transcripts.component.ts
  src/app/admin/components/transformed-media/search-transformed-media-form/search-transformed-media-form.component.ts
  src/app/admin/components/transformed-media/search-transformed-media/search-transformed-media.component.ts
  src/app/admin/components/users/user-transcripts/user-transcripts.component.ts
  src/app/admin/services/transcription-admin/transcription-admin.service.spec.ts
  src/app/admin/services/transcription-admin/transcription-admin.service.ts
  src/app/core/components/common/courthouse/courthouse.component.spec.ts
  src/app/core/components/common/courthouse/courthouse.component.ts
  src/app/portal/components/search/case-search-form/case-search-form.component.ts
  src/app/portal/components/search/search.component.spec.ts
  src/app/portal/components/search/search.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-1757

#1762 DMP-4369 Admin transcript searches limit changed to 2000
  src/app/admin/components/transcripts/search-transcripts-form/search-transcripts-form.component.ts
Labels: ns:darts-modernisation, prd:darts

#1748 DMP-4371 Case search form validation
  cypress/e2e/functional/case-search-spec.cy.js
  src/app/admin/constants/case-search-form-error-messages.ts
  src/app/portal/components/search/case-search-form/case-search-form.component.html
  src/app/portal/components/search/case-search-form/case-search-form.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-1748

#1764 Set validation length limits from 256 to 255 across multiple forms
  src/app/admin/components/courthouses/courthouse-search-form/courthouse-search-form.component.ts
  src/app/admin/components/file-deletion/file-hide-or-delete/file-hide-or-delete.component.ts
  src/app/admin/components/users/create-user/create-update-user-form/create-update-user-form.component.ts
  src/app/admin/components/users/user-search-form/user-search-form.component.ts
Labels: ns:darts-modernisation, prd:darts

#1754 DMP-4129 add approved on column to transcription tables
  cypress.config.js
  cypress/e2e/functional/admin-portal/user-record-spec.cy.js
  cypress/e2e/functional/commands.js
  darts-api-stub/admin/transcriptions/transcriptions.js
  darts-api-stub/transcriptions/transcriptions.js
  src/app/admin/components/users/user-transcripts/user-transcripts.component.html
  src/app/admin/components/users/user-transcripts/user-transcripts.component.ts
  src/app/admin/models/transcription/transcription-data.interface.ts
  src/app/admin/models/transcription/transcription.ts
  src/app/admin/services/transcription-admin/transcription-admin.service.ts
  src/app/portal/components/transcriptions/transcription-requests/transcription-requests.component.html
  src/app/portal/components/transcriptions/transcriptions.component.html
  src/app/portal/components/transcriptions/transcriptions.component.spec.ts
  src/app/portal/components/transcriptions/transcriptions.component.ts
  src/app/portal/components/your-work/your-work.component.html
  src/app/portal/components/your-work/your-work.component.spec.ts
  src/app/portal/constants/transcription-columns.ts
  src/app/portal/models/transcriptions/transcript-request.type.ts
  src/app/portal/models/transcriptions/user-transcription-request.interface.ts
  src/app/portal/services/transcription/transcription.service.ts
Labels: ns:darts-modernisation, prd:darts, enable_keep_helm, rel:darts-portal-pr-1754

#1766 DMP-4568 Added error summary to unhide associated audio screen
  src/app/admin/components/file-deletion/file-unhide-or-undelete/file-unhide-or-undelete.component.html
  src/app/admin/components/file-deletion/file-unhide-or-undelete/file-unhide-or-undelete.component.ts
Labels: ns:darts-modernisation, prd:darts

#1765 DMP-4442/4444 - File deletion audio updates
  cypress/e2e/functional/admin-portal/file-deletion-spec.cy.js
  cypress/e2e/functional/admin-portal/hide-or-delete-file-spec.cy.js
  darts-api-stub/admin/medias/medias.js
  src/app/admin/admin.routes.ts
  src/app/admin/components/automated-tasks/view-automated-tasks/view-automated-tasks.component.html
  src/app/admin/components/file-deletion/approve-reject-file-delete/approve-reject-file-delete.component.html
  src/app/admin/components/file-deletion/approve-reject-file-delete/approve-reject-file-delete.component.scss
  src/app/admin/components/file-deletion/approve-reject-file-delete/approve-reject-file-delete.component.spec.ts
  src/app/admin/components/file-deletion/approve-reject-file-delete/approve-reject-file-delete.component.ts
  src/app/admin/components/file-deletion/audio-file-delete/audio-file-delete.component.html
  src/app/admin/components/file-deletion/audio-file-delete/audio-file-delete.component.scss
  src/app/admin/components/file-deletion/audio-file-delete/audio-file-delete.component.spec.ts
  src/app/admin/components/file-deletion/audio-file-delete/audio-file-delete.component.ts
  src/app/admin/components/file-deletion/audio-file-results/audio-file-results.component.html
  src/app/admin/components/file-deletion/audio-file-results/audio-file-results.component.scss
  src/app/admin/components/file-deletion/audio-file-results/audio-file-results.component.spec.ts
  src/app/admin/components/file-deletion/audio-file-results/audio-file-results.component.ts
  src/app/admin/components/file-deletion/file-deletion.component.spec.ts
  src/app/admin/components/file-deletion/file-deletion.component.ts
  src/app/admin/components/file-deletion/file-unhide-or-undelete/file-unhide-or-undelete.component.spec.ts
  src/app/admin/components/file-deletion/file-unhide-or-undelete/file-unhide-or-undelete.component.ts
  src/app/admin/components/file-deletion/transcript-file-delete/transcript-file-delete.component.spec.ts
  src/app/admin/components/file-deletion/transcript-file-delete/transcript-file-delete.component.ts
  src/app/admin/components/transformed-media/associated-audio-table/associated-audio-table.component.ts
  src/app/admin/models/file-deletion/audio-file-marked-deletion.interface.ts
  src/app/admin/models/file-deletion/audio-file-marked-deletion.type.ts
  src/app/admin/models/file-deletion/media.interface.ts
  src/app/admin/models/file-deletion/media.type.ts
  src/app/admin/models/transformed-media/admin-action-data.interface.ts
  src/app/admin/models/transformed-media/admin-action.ts
  src/app/admin/services/file-deletion/file-deletion.service.spec.ts
  src/app/admin/services/file-deletion/file-deletion.service.ts
  src/app/core/directives/govuk-summary-list/govuk-summary-container.directive.spec.ts
  src/app/core/directives/govuk-summary-list/govuk-summary-container.directive.ts
  src/app/core/directives/govuk-summary-list/govuk-summary-list.directive.ts
  src/app/core/directives/govuk-summary-list/govuk-summary.directive.ts
  src/app/core/directives/govuk-summary-list/index.ts
  src/app/core/pipes/join.ts
  src/app/core/validators/checkbox-true.validator.ts
Labels: ns:darts-modernisation, prd:darts

#1770 DMP-4561 Removing sort on load as sorting is handled in BE now
  src/app/admin/components/search/event-search-results/event-search-results.component.ts
  src/app/portal/components/case/case-file/case-events-table/case-events-table.component.ts
  src/app/portal/components/case/case-retention-date/case-retention-date.component.ts
Labels: ns:darts-modernisation, prd:darts

#1758 DMP-4130 - Added approved on to details tables for transcript requests
  cypress/e2e/functional/admin-portal/transcript-requests-spec.cy.js
  darts-api-stub/transcriptions/transcriptions.js
  src/app/admin/components/transcripts/view-transcription-document/transcript-file-basic-detail/transcript-file-basic-detail.component.ts
  src/app/admin/services/transcription-admin/transcription-admin.service.spec.ts
  src/app/admin/services/transcription-admin/transcription-admin.service.ts
  src/app/portal/models/transcriptions/transcription-details.interface.ts
  src/app/portal/models/transcriptions/transcription-details.type.ts
  src/app/portal/services/mapping/mapping.service.ts
  src/app/portal/services/transcription/transcription.service.spec.ts
  src/app/portal/services/transcription/transcription.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-1758

#1768 DMP-3956 Bulk download, validation for delete, download
  cypress/e2e/functional/your-audio-spec.cy.js
  src/app/portal/components/audios/audios.component.html
  src/app/portal/components/audios/audios.component.scss
  src/app/portal/components/audios/audios.component.spec.ts
  src/app/portal/components/audios/audios.component.ts
Labels: ns:darts-modernisation, prd:darts

#1771 Ignore errors when fetching transcriber counts
  src/app/core/services/error/error-message.service.ts
Labels: ns:darts-modernisation, prd:darts

#1778 Angular 19 fixes
  cypress/e2e/functional/admin-portal/courthouses-spec.cy.js
  cypress/e2e/functional/admin-portal/users-spec.cy.js
  src/app/admin/components/courthouses/courthouses.component.ts
  src/app/admin/components/users/user-search-results/user-search-results.component.html
  src/app/admin/components/users/user-search-results/user-search-results.component.spec.ts
  src/app/admin/components/users/user-search-results/user-search-results.component.ts
  src/app/admin/components/users/users.component.html
  src/app/admin/components/users/users.component.ts
  src/styles.scss
  yarn.lock
Labels: ns:darts-modernisation, prd:darts

#1781 Admin group search retain results, inputs
  cypress/e2e/functional/admin-portal/groups-spec.cy.js
  src/app/admin/components/groups/groups.component.ts
Labels: ns:darts-modernisation, prd:darts

#1782 DMP-4318/4644 Sorting fixes
  cypress/e2e/functional/request-audio-spec.cy.js
  src/app/core/components/common/data-table/data-table.component.ts
  src/app/core/constants/datetime-keys.ts
  src/app/portal/components/hearing/events-and-audio/events-and-audio.component.spec.ts
  src/app/portal/components/hearing/events-and-audio/events-and-audio.component.ts
  src/app/portal/services/case/case.service.ts
Labels: ns:darts-modernisation, prd:darts
