Repository hmcts/darts-portal, pull requests merged in 2025-05, with the labels that each got.

#1998 DMP-3223 Case events on admin portal
  cypress/e2e/functional/admin-portal/case-file-spec.cy.js
  darts-api-stub/cases/case.js
  src/app/admin/components/case/case.component.html
  src/app/admin/components/case/case.component.spec.ts
  src/app/admin/components/case/case.component.ts
  src/app/admin/components/search/search-form/search-form.component.spec.ts
  src/app/admin/components/search/search-form/search-form.component.ts
  src/app/admin/components/search/search.component.html
  src/app/admin/components/transcripts/search-transcripts-form/search-transcripts-form.component.spec.ts
  src/app/admin/components/transcripts/search-transcripts-form/search-transcripts-form.component.ts
  src/app/admin/components/transcripts/transcripts.component.html
  src/app/admin/components/transformed-media/search-transformed-media-form/search-transformed-media-form.component.spec.ts
  src/app/admin/components/transformed-media/search-transformed-media-form/search-transformed-media-form.component.ts
  src/app/admin/components/transformed-media/search-transformed-media/search-transformed-media.component.html
  src/app/portal/components/case/case-file/case-events-table/case-events-table.component.html
  src/app/portal/components/case/case-file/case-events-table/case-events-table.component.spec.ts
  src/app/portal/components/case/case-file/case-events-table/case-events-table.component.ts
  src/app/portal/components/case/case.component.html
  src/app/portal/components/case/case.component.spec.ts
  src/app/portal/components/case/case.component.ts
  src/app/portal/components/search/case-search-form/case-search-form.component.spec.ts
  src/app/portal/components/search/case-search-form/case-search-form.component.ts
  src/app/portal/components/search/search.component.html
  src/app/portal/models/events/case-event-data.interface.ts
  src/app/portal/models/events/case-event.ts
  src/app/portal/services/case-events-loader/case-events-loader.service.spec.ts
  src/app/portal/services/case-events-loader/case-events-loader.service.ts
  src/app/portal/services/case/case.service.spec.ts
  src/app/portal/services/case/case.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-1998

#2004 DMP-4181 DMP-4887 handle no current versions on audio and event version screen
  src/app/admin/components/audio-file/show-versions/show-versions.component.html
  src/app/admin/components/audio-file/show-versions/show-versions.component.spec.ts
  src/app/admin/components/audio-file/show-versions/show-versions.component.ts
  src/app/admin/components/events/show-versions/show-versions.component.html
  src/app/admin/components/events/show-versions/show-versions.component.spec.ts
  src/app/admin/components/events/show-versions/show-versions.component.ts
  src/app/admin/facades/events/events-facade.service.spec.ts
  src/app/admin/facades/events/events-facade.service.ts
  src/app/admin/models/events/event-versions.ts
  src/app/admin/models/transformed-media/audio-versions.ts
  src/app/admin/services/events/events.service.spec.ts
  src/app/admin/services/events/events.service.ts
  src/app/admin/services/transformed-media/transformed-media.service.spec.ts
  src/app/admin/services/transformed-media/transformed-media.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-2004

#2008 DMP-5030 Hide transformed media delete button when no results exist
  src/app/admin/components/transformed-media/transformed-media-search-results/transformed-media-search-results.component.html
  src/app/admin/components/transformed-media/transformed-media-search-results/transformed-media-search-results.component.spec.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-2008

#2005 DMP-4814 date format change from d to dd
  cypress/e2e/functional/admin-portal/audio-file-details-spec.cy.js
  cypress/e2e/functional/admin-portal/transcript-requests-spec.cy.js
  src/app/admin/components/case/case-file/case-file.component.html
  src/app/admin/components/file-deletion/audio-file-delete/audio-file-delete.component.html
  src/app/admin/components/file-deletion/audio-file-results/audio-file-results.component.html
  src/app/admin/components/file-deletion/transcripts-for-deletion/transcripts-for-deletion.component.html
  src/app/admin/components/hearing/hearing-file/hearing-file.component.html
  src/app/admin/components/transformed-media/associated-audio-table/associated-audio-table.component.html
  src/app/core/components/common/expired-banner/expired-banner.component.html
  src/app/portal/components/audios/audio-view/audio-view.component.html
  src/app/portal/components/case/case-file/case-file.component.html
  src/app/portal/components/hearing/hearing-file/hearing-file.component.html
  src/app/portal/components/hearing/hearing.component.html
  src/app/portal/components/hearing/order-confirmation/order-confirmation.component.html
  src/app/portal/components/hearing/request-transcript/request-transcript.component.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-2005

#2003 DMP-3224 Transcripts tab case file admin
  cypress/e2e/functional/admin-portal/case-file-spec.cy.js
  darts-api-stub/cases/case.js
  src/app/admin/components/case/case.component.html
  src/app/admin/components/case/case.component.spec.ts
  src/app/admin/components/case/case.component.ts
  src/app/admin/components/hearing/hearing.component.spec.ts
  src/app/portal/components/case/case-file/case-transcripts-table/case-transcripts-table.component.html
  src/app/portal/components/case/case-file/case-transcripts-table/case-transcripts-table.component.spec.ts
  src/app/portal/components/case/case-file/case-transcripts-table/case-transcripts-table.component.ts
  src/app/portal/components/case/case.component.spec.ts
  src/app/portal/components/hearing/hearing.component.spec.ts
  src/app/portal/models/transcriptions/transcript.interface.ts
  src/app/portal/models/transcriptions/transcript.type.ts
  src/app/portal/models/transcriptions/transcripts-row.type.ts
  src/app/portal/services/case/case.service.spec.ts
  src/app/portal/services/case/case.service.ts
  src/app/portal/services/mapping/mapping.service.spec.ts
  src/app/portal/services/mapping/mapping.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-2003

#1981 DMP-4960: Empty author on transcription comment should not display System user
  src/app/admin/facades/transcript/transcript-facade.service.spec.ts
  src/app/admin/facades/transcript/transcript-facade.service.ts
  src/app/admin/models/transcription/transcription-workflow.ts
  src/app/core/components/common/timeline/timeline.component.html
  src/app/core/components/common/timeline/timeline.component.spec.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-1981

#2014 DMP-5059 Fixing get audio navigation for transcriptions with no hearing
  src/app/portal/components/transcriptions/assign-transcript/assign-transcript.component.ts
  src/app/portal/components/your-work/upload-transcript/upload-transcript.component.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-2014

#2009 DMP-4965 Added hearing id links where possible
  src/app/admin/components/search/hearing-search-results/hearing-search-results.component.html
  src/app/admin/components/transcripts/search-completed-transcripts-results/search-completed-transcripts-results.component.html
  src/app/admin/components/transcripts/search-completed-transcripts-results/search-completed-transcripts-results.component.spec.ts
  src/app/admin/components/transcripts/search-completed-transcripts-results/search-completed-transcripts-results.component.ts
  src/app/admin/components/transcripts/search-transcripts-results/search-transcripts-results.component.html
  src/app/admin/components/transcripts/search-transcripts-results/search-transcripts-results.component.ts
  src/app/admin/components/transformed-media/transformed-media-search-results/transformed-media-search-results.component.html
  src/app/admin/components/transformed-media/transformed-media-search-results/transformed-media-search-results.component.ts
  src/app/admin/components/transformed-media/view-transformed-media/view-transformed-media.component.html
  src/app/admin/models/transcription/transcription-data.interface.ts
  src/app/admin/models/transcription/transcription-document-search-result.ts
  src/app/admin/models/transcription/transcription.ts
  src/app/admin/services/transcription-admin/transcription-admin.service.spec.ts
  src/app/admin/services/transcription-admin/transcription-admin.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-2009

#2024 Handle empty hearing on admin portal transcript documents search
  src/app/admin/components/transcripts/search-completed-transcripts-results/search-completed-transcripts-results.component.html
  src/app/admin/components/transcripts/search-completed-transcripts-results/search-completed-transcripts-results.component.ts
  src/app/admin/components/transcripts/search-transcripts-results/search-transcripts-results.component.html
  src/app/admin/components/transcripts/transcripts.component.html
  src/app/admin/models/transcription/transcription-document-search-result.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-2024

#2028 DMP-4814 remove spelling mistake
  src/app/portal/components/hearing/add-annotation/add-annotation.component.html
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-2028

#2029 Using MoJ frontend v4
  package.json
  yarn.lock
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-2029

#2027 DMP-5064 Super user permissions for group page admin
  cypress/e2e/functional/admin-portal/group-record-spec.cy.js
  src/app/admin/admin.routes.ts
  src/app/admin/components/groups/group-courthouses/group-courthouses.component.html
  src/app/admin/components/groups/group-courthouses/group-courthouses.component.ts
  src/app/admin/components/groups/group-record/group-record.component.html
  src/app/admin/components/groups/group-record/group-record.component.spec.ts
  src/app/admin/components/groups/group-record/group-record.component.ts
  src/app/admin/components/groups/group-users/group-users.component.html
  src/app/admin/components/groups/group-users/group-users.component.ts
  src/app/admin/components/groups/groups.component.html
  src/app/admin/components/groups/groups.component.spec.ts
  src/app/admin/components/groups/groups.component.ts
  src/app/core/components/layout/header/admin-navigation/admin-navigation.component.html
  src/app/core/services/user/user.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-2027

#2032 Improvements to auth guard for admin routes
  src/app/app.routes.spec.ts
  src/app/core/guards/auth/auth.guard.spec.ts
  src/app/core/guards/auth/auth.guard.ts
  src/app/core/services/user/user.service.spec.ts
  src/app/core/services/user/user.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-2032

#2025 DMP-3970 judge case file screen
  cypress/e2e/functional/case-file-spec.cy.js
  darts-api-stub/cases/case.js
  src/app/core/components/common/see-more-list/see-more-list.component.html
  src/app/core/components/common/see-more-list/see-more-list.component.scss
  src/app/core/components/common/see-more-list/see-more-list.component.spec.ts
  src/app/core/components/common/see-more-list/see-more-list.component.ts
  src/app/portal/components/case/case-file/case-file.component.html
  src/app/portal/components/case/case-file/case-file.component.scss
  src/app/portal/components/case/case-file/case-file.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-2025

#2034 DMP-5079 Preventing superuser changing the status of a transcript request
  src/app/admin/admin.routes.ts
  src/app/admin/services/transcription-admin/transcription-admin.service.spec.ts
  src/app/admin/services/transcription-admin/transcription-admin.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-2034

#2035 DMP-4982 Fixing courthouse sort order on group courthouse screen
  src/app/admin/services/courthouses/courthouse.service.spec.ts
  src/app/admin/services/courthouses/courthouses.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-2035

#2040 DMP-5042: (Dev only) Ignore system users in user endpoints
  src/app/admin/components/courthouses/courthouse-record/courthouse-record.component.spec.ts
  src/app/admin/components/users/user-groups/assign-groups/assign-groups.component.spec.ts
  src/app/admin/components/users/user-groups/remove-groups/remove-groups.component.spec.ts
  src/app/admin/components/users/user-groups/user-groups/user-groups.component.spec.ts
  src/app/admin/components/users/user-record/user-record.component.spec.ts
  src/app/admin/models/users/user-data.interface.ts
  src/app/admin/models/users/user.type.ts
  src/app/admin/services/user-admin/user-admin.service.spec.ts
  src/app/admin/services/user-admin/user-admin.service.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-2040

#2036 DMP-4981 handle back links in courthouse record
  src/app/admin/components/courthouses/courthouse-record/courthouse-record.component.html
  src/app/admin/components/courthouses/courthouse-record/courthouse-record.component.spec.ts
  src/app/admin/components/courthouses/courthouse-record/courthouse-record.component.ts
Labels: ns:darts-modernisation, prd:darts, enable_keep_helm, rel:darts-portal-pr-2036

#2038 DMP-5033 Reset form selections on order confirmation
  src/app/portal/components/hearing/events-and-audio/events-and-audio.component.html
  src/app/portal/components/hearing/events-and-audio/events-and-audio.component.spec.ts
  src/app/portal/components/hearing/events-and-audio/events-and-audio.component.ts
  src/app/portal/components/hearing/hearing.component.html
  src/app/portal/components/hearing/hearing.component.ts
  src/app/portal/components/hearing/request-playback-audio/request-playback-audio.component.spec.ts
  src/app/portal/components/hearing/request-playback-audio/request-playback-audio.component.ts
Labels: ns:darts-modernisation, prd:darts, enable_keep_helm, rel:darts-portal-pr-2038

#2037 DMP-5062 Added active tab service for case file admin
  src/app/admin/components/case/case.component.html
  src/app/admin/components/case/case.component.ts
  src/app/portal/components/search/case-search-results/case-search-results.component.html
  src/app/portal/components/search/case-search-results/case-search-results.component.spec.ts
  src/app/portal/components/search/case-search-results/case-search-results.component.ts
Labels: ns:darts-modernisation, prd:darts, enable_keep_helm, rel:darts-portal-pr-2037

#2039 Handling errors with dynamically importing modules
  package.json
  server/app-config.ts
  server/utils/version.ts
  src/app/core/services/app-config/app-config.service.spec.ts
  src/app/core/services/app-config/app-config.service.ts
  src/app/core/services/dynatrace/dynatrace.service.spec.ts
  src/app/core/services/error/error-handler.service.spec.ts
  src/app/core/services/error/error-handler.service.ts
  yarn.lock
Labels: ns:darts-modernisation, prd:darts, enable_keep_helm, rel:darts-portal-pr-2039

#2052 DMP-5033 Resetting audio request "request type" correctly
  src/app/portal/components/hearing/request-playback-audio/request-playback-audio.component.ts
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-2052

#2053 reverting to 4.0.0 as <4.0.1 breaks sort arrows
  package.json
  yarn.lock
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-2053

#2059 Revert "Update dependency @ministryofjustice/frontend to v4.0.2"
  package.json
  renovate.json
  yarn.lock
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-2059

#2063 Temporarily disable automerge of Renovate
  renovate.json
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-2063
