Repository hmcts/darts-portal, pull requests merged in 2025-07, with the labels that each got.

#2067 DMP-4888 update assigned groups message to newly assigned count
  cypress/e2e/functional/admin-portal/user-record-spec.cy.js
  src/app/admin/components/users/user-groups/assign-groups/assign-groups.component.spec.ts
  src/app/admin/components/users/user-groups/assign-groups/assign-groups.component.ts
  src/app/admin/components/users/user-record/user-record.component.html
  src/app/admin/components/users/user-record/user-record.component.spec.ts
  src/app/admin/components/users/user-record/user-record.component.ts
Labels: ns:darts-modernisation, prd:darts, enable_keep_helm, rel:darts-portal-pr-2067

#2043 DMP-5043 Improvements for validation of group name
  src/app/core/validators/group-name.validator.spec.ts
  src/app/core/validators/group-name.validator.ts
Labels: ns:darts-modernisation, prd:darts, enable_keep_helm, rel:darts-portal-pr-2043

#2046 DMP-5081 Event mapping id and inactive checks
  src/app/admin/components/courthouses/courthouse-record/courthouse-record.component.ts
  src/app/admin/components/system-configuration/event-mappings/add-update-event-mapping/add-update-event-mapping.component.spec.ts
  src/app/admin/components/system-configuration/event-mappings/add-update-event-mapping/add-update-event-mapping.component.ts
  yarn.lock
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-2046

#2088 DMP-5066 - Fixing long case numbers flowing into other table cells
  src/styles.scss
Labels: ns:darts-modernisation, prd:darts, enable_keep_helm, rel:darts-portal-pr-2088

#2081 DMP-5003 Changes to hyperlink users only if they are non-system users
  src/app/admin/components/audio-file/advanced-audio-file-details/advanced-audio-file-details.component.html
  src/app/admin/components/audio-file/advanced-audio-file-details/advanced-audio-file-details.component.spec.ts
  src/app/admin/components/audio-file/audio-file.component.spec.ts
  src/app/admin/components/audio-file/audio-file.component.ts
  src/app/admin/components/automated-tasks/view-automated-tasks/view-automated-tasks.component.spec.ts
  src/app/admin/components/automated-tasks/view-automated-tasks/view-automated-tasks.component.ts
  src/app/admin/components/transcripts/view-transcription-document/transcript-file-advanced-detail/transcript-file-advanced-detail.component.spec.ts
  src/app/admin/components/transcripts/view-transcription-document/transcript-file-advanced-detail/transcript-file-advanced-detail.component.ts
  src/app/admin/components/transcripts/view-transcription-document/view-transcription-document.component.spec.ts
  src/app/admin/components/transcripts/view-transcription-document/view-transcription-document.component.ts
  src/app/admin/facades/transcript/transcript-facade.service.spec.ts
  src/app/admin/facades/transcript/transcript-facade.service.ts
  src/app/admin/models/transcription/transcription-assignee.ts
  src/app/admin/models/transcription/transcription-document.ts
  src/app/admin/models/transcription/transcription-requestor.ts
  src/app/admin/models/transformed-media/admin-action.ts
  src/app/admin/models/transformed-media/audio-file.ts
  src/app/admin/services/transcription-admin/transcription-admin.service.spec.ts
  src/app/admin/services/transcription-admin/transcription-admin.service.ts
  src/app/admin/services/user-admin/user-admin.service.spec.ts
  src/app/admin/services/user-admin/user-admin.service.ts
  src/app/core/components/common/timeline/timeline.component.html
  src/app/core/components/common/timeline/timeline.component.spec.ts
  src/app/core/models/timeline/timeline.type.ts
  src/app/dev/dev.component.ts
Labels: ns:darts-modernisation, prd:darts, enable_keep_helm, rel:darts-portal-pr-2081

#2115 Express-session > on-headers vulnerability
  package.json
  yarn.lock
Labels: ns:darts-modernisation, prd:darts, rel:darts-portal-pr-2115
